-- SQL INSERT statements for MŌVE fitness coaching app
-- Dutch/Belgian supermarket products: Zuivel (Dairy), Granen (Grains), Brood (Bread)
-- Generated for food_products table

-- =====================================================================
-- ZUIVEL (DAIRY) - 60 PRODUCTS
-- =====================================================================

-- Melk (5 products)
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Whole Milk', 'Volle melk', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'zuivel', 250, '1 glas', 64, 3.2, 4.8, 3.6, 0, 4.8, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Semi-Skimmed Milk', 'Halfvolle melk', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'zuivel', 250, '1 glas', 49, 3.4, 4.8, 1.8, 0, 4.8, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Skimmed Milk', 'Magere melk', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'zuivel', 250, '1 glas', 34, 3.4, 4.9, 0.1, 0, 4.9, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Buttermilk', 'Karnemelk', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'zuivel', 250, '1 glas', 37, 3.5, 4.0, 0.5, 0, 3.8, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Chocolate Milk', 'Chocolademelk', 'Friesche Vlag', 'supermarket', 'albert_heijn', NULL, 'zuivel', 250, '1 glas', 79, 3.2, 11.5, 2.5, 0, 11.0, FALSE);

-- Yoghurt (15 products)
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Greek Yoghurt Plain', 'Griekse yoghurt naturel', 'Fage', 'supermarket', 'albert_heijn', NULL, 'zuivel', 150, '1 bakje', 59, 10.2, 3.3, 0.4, 0, 0.7, TRUE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Greek Yoghurt Honey', 'Griekse yoghurt honing', 'Fage', 'supermarket', 'albert_heijn', NULL, 'zuivel', 150, '1 bakje', 72, 9.8, 8.2, 0.4, 0, 7.5, TRUE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Low Fat Yoghurt Plain', 'Magere yoghurt naturel', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'zuivel', 125, '1 bakje', 42, 3.8, 4.2, 0.5, 0, 3.5, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Full Fat Yoghurt Plain', 'Volle yoghurt naturel', 'Arla', 'supermarket', 'albert_heijn', NULL, 'zuivel', 125, '1 bakje', 66, 3.5, 4.3, 3.9, 0, 4.0, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Arla Skyr Vanilla', 'Arla Skyr vanille', 'Arla', 'supermarket', 'albert_heijn', NULL, 'zuivel', 150, '1 bakje', 64, 10.0, 5.8, 0.2, 0, 5.2, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Danio Plain', 'Danio naturel', 'Danone', 'supermarket', 'albert_heijn', NULL, 'zuivel', 125, '1 bakje', 55, 4.2, 4.1, 2.8, 0, 3.8, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Activia Natural', 'Activia naturel', 'Danone', 'supermarket', 'albert_heijn', NULL, 'zuivel', 125, '1 bakje', 48, 3.6, 4.5, 1.5, 0.5, 4.0, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Optimel Natural', 'Optimel naturel', 'Optimel', 'supermarket', 'albert_heijn', NULL, 'zuivel', 150, '1 bakje', 51, 3.9, 3.8, 2.0, 0, 3.5, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Arla Protein Yoghurt', 'Arla Protein yoghurt', 'Arla', 'supermarket', 'albert_heijn', NULL, 'zuivel', 150, '1 bakje', 75, 15.0, 3.5, 0.3, 0, 3.0, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Danone YoPro Vanilla', 'Danone YoPro vanille', 'Danone', 'supermarket', 'albert_heijn', NULL, 'zuivel', 150, '1 bakje', 76, 14.5, 4.8, 0.5, 0, 4.2, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Ehrmann High Protein', 'Ehrmann High Protein', 'Ehrmann', 'supermarket', 'albert_heijn', NULL, 'zuivel', 150, '1 bakje', 80, 16.0, 3.2, 0.3, 0, 2.8, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Strawberry Yoghurt', 'Aardbeien yoghurt', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'zuivel', 125, '1 bakje', 63, 3.5, 11.2, 1.2, 0, 10.5, FALSE);

-- Kwark (5 products)
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Low Fat Quark Plain', 'Magere kwark naturel', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'zuivel', 150, '1 potje', 70, 11.0, 2.5, 0.3, 0, 1.5, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Full Fat Quark Plain', 'Volle kwark naturel', 'Almhof', 'supermarket', 'albert_heijn', NULL, 'zuivel', 150, '1 potje', 98, 10.5, 2.8, 5.5, 0, 1.8, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Quark with Fruit Mix', 'Kwark met vruchten mix', 'Almhof', 'supermarket', 'albert_heijn', NULL, 'zuivel', 150, '1 potje', 85, 10.2, 8.5, 2.0, 0, 7.8, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Quark with Strawberry', 'Kwark met aardbei', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'zuivel', 150, '1 potje', 82, 10.0, 8.2, 1.8, 0, 7.5, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Quark with Blueberry', 'Kwark met blauwebessen', 'Almhof', 'supermarket', 'albert_heijn', NULL, 'zuivel', 150, '1 potje', 84, 10.1, 8.5, 1.9, 0.5, 7.8, FALSE);

-- Kaas (20 products)
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Young Gouda Cheese', 'Jong Goudse kaas', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'zuivel', 30, '1 plak', 356, 25.0, 1.3, 28.0, 0, 0.7, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Matured Gouda Cheese', 'Belegen Goudse kaas', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'zuivel', 30, '1 plak', 376, 26.0, 0.5, 30.5, 0, 0.3, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Old Gouda Cheese', 'Oude Goudse kaas', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'zuivel', 30, '1 plak', 395, 27.0, 0.3, 32.0, 0, 0.2, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Gouda 30+ Cheese', 'Goudse kaas 30+', 'Beemster', 'supermarket', 'albert_heijn', NULL, 'zuivel', 30, '1 plak', 368, 26.5, 0.4, 29.5, 0, 0.2, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Edam Cheese', 'Edammer kaas', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'zuivel', 30, '1 plak', 356, 24.5, 1.0, 28.5, 0, 0.6, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Mozzarella', 'Mozzarella', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'zuivel', 100, '1 portion', 280, 28.0, 3.1, 17.0, 0, 0.7, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Feta Cheese', 'Feta kaas', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'zuivel', 30, '1 portion', 265, 17.0, 4.1, 21.0, 0, 1.2, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Brie Cheese', 'Brie kaas', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'zuivel', 30, '1 portion', 334, 19.5, 0.7, 27.5, 0, 0.4, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Camembert Cheese', 'Camembert kaas', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'zuivel', 30, '1 portion', 340, 20.0, 0.5, 28.0, 0, 0.3, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Cottage Cheese Plain', 'Cottage cheese naturel', 'Arla', 'supermarket', 'albert_heijn', NULL, 'zuivel', 100, '1 potje', 98, 11.5, 3.9, 4.3, 0, 2.8, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Ricotta Cheese', 'Ricotta kaas', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'zuivel', 100, '1 potje', 174, 12.6, 3.0, 13.0, 0, 2.5, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Mascarpone Cheese', 'Mascarpone kaas', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'zuivel', 100, '1 potje', 452, 6.5, 4.5, 47.0, 0, 3.8, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Philadelphia Cream Cheese', 'Philadelphia roomkaas', 'Philadelphia', 'supermarket', 'albert_heijn', NULL, 'zuivel', 100, '1 potje', 342, 5.9, 4.1, 35.0, 0, 3.5, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Cream Cheese Plain', 'Roomkaas naturel', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'zuivel', 100, '1 potje', 340, 5.8, 4.0, 34.5, 0, 3.4, FALSE);

-- Boter, margarine, halvarine (4 products)
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Becel Margarine', 'Becel margarine', 'Becel', 'supermarket', 'albert_heijn', NULL, 'zuivel', 10, '1 portie', 717, 0.5, 0.5, 80.0, 0, 0.1, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Blue Band Margarine', 'Blue Band margarine', 'Blue Band', 'supermarket', 'albert_heijn', NULL, 'zuivel', 10, '1 portie', 718, 0.3, 0.3, 80.0, 0, 0.1, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Halvarine Room', 'Halvarine roomboter', 'Becel', 'supermarket', 'albert_heijn', NULL, 'zuivel', 10, '1 portie', 568, 0.4, 0.4, 63.0, 0, 0.1, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Roomboter Pure Butter', 'Roomboter zuivere boter', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'zuivel', 10, '1 portie', 717, 0.5, 0.1, 81.0, 0, 0.1, FALSE);

-- Room (cream products) (6 products)
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Whipping Cream', 'Slagroom', 'Campina', 'supermarket', 'albert_heijn', NULL, 'zuivel', 15, '1 lepel', 340, 2.0, 2.8, 35.0, 0, 2.6, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Cooking Cream', 'Kookroom', 'Campina', 'supermarket', 'albert_heijn', NULL, 'zuivel', 15, '1 lepel', 302, 2.2, 3.5, 31.0, 0, 3.2, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Creme Fraiche', 'Crème fraîche', 'Campina', 'supermarket', 'albert_heijn', NULL, 'zuivel', 15, '1 lepel', 340, 1.8, 2.5, 35.5, 0, 2.2, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Sour Cream', 'Zure room', 'Campina', 'supermarket', 'albert_heijn', NULL, 'zuivel', 15, '1 lepel', 193, 3.6, 4.3, 19.0, 0, 4.0, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Whipped Cream Spray', 'Slagroom spuitbus', 'Campina', 'supermarket', 'albert_heijn', NULL, 'zuivel', 10, '1 portie', 290, 1.5, 6.0, 30.0, 0, 5.5, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Greek Style Yoghurt Cream', 'Griekse stijl room yoghurt', 'Fage', 'supermarket', 'albert_heijn', NULL, 'zuivel', 100, '1 potje', 45, 3.8, 2.5, 1.5, 0, 1.8, FALSE);

-- Vla en pudding (4 products)
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Vanilla Custard Vla', 'Vanille vla', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'zuivel', 150, '1 potje', 98, 3.2, 15.5, 2.0, 0, 14.8, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Chocolate Custard Vla', 'Chocolade vla', 'Campina', 'supermarket', 'albert_heijn', NULL, 'zuivel', 150, '1 potje', 115, 3.0, 18.5, 2.5, 0, 18.0, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Chocolate Pudding', 'Chocolade pudding', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'zuivel', 150, '1 potje', 128, 2.8, 20.5, 3.5, 0, 19.8, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Vanilla Pudding', 'Vanille pudding', 'Campina', 'supermarket', 'albert_heijn', NULL, 'zuivel', 150, '1 potje', 112, 3.1, 17.2, 2.8, 0, 16.5, FALSE);

-- =====================================================================
-- GRANEN (GRAINS/CEREALS) - 40 PRODUCTS
-- =====================================================================

-- Havermout (3 products)
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Fine Oatmeal', 'Fijne havermout', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'granen', 40, '½ kop', 389, 17.0, 66.3, 6.9, 10.6, 0.8, TRUE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Coarse Oatmeal', 'Grove havermout', 'Quaker', 'supermarket', 'albert_heijn', NULL, 'granen', 40, '½ kop', 389, 16.9, 66.5, 6.8, 10.4, 1.0, TRUE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Overnight Oats', 'Overnight oats mix', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'granen', 50, '1 potje', 368, 12.0, 62.0, 7.5, 9.5, 15.0, TRUE);

-- Muesli (3 products)
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Crunchy Muesli', 'Krokante muesli', 'Jordan''s', 'supermarket', 'albert_heijn', NULL, 'granen', 50, '½ kop', 425, 10.2, 60.0, 15.0, 8.0, 25.0, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Untoasted Muesli', 'Ongebrande muesli', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'granen', 50, '½ kop', 371, 10.5, 65.0, 5.2, 7.5, 18.0, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Jordan''s Muesli High Fibre', 'Jordan''s muesli hoog in vezels', 'Jordan''s', 'supermarket', 'albert_heijn', NULL, 'granen', 50, '½ kop', 348, 11.0, 62.5, 4.5, 10.5, 15.5, FALSE);

-- Cornflakes en populaire graanvlokken (6 products)
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Cornflakes Original', 'Cornflakes origineel', 'Kellogg''s', 'supermarket', 'albert_heijn', NULL, 'granen', 30, '1 kop', 386, 8.0, 84.0, 2.0, 3.0, 3.0, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Cornflakes AH', 'Cornflakes Albert Heijn', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'granen', 30, '1 kop', 378, 7.5, 85.0, 1.5, 2.5, 3.5, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Crunchy Cereal', 'Krokante graanvlokken', 'Kellogg''s', 'supermarket', 'albert_heijn', NULL, 'granen', 40, '¾ kop', 430, 8.5, 72.0, 13.0, 3.5, 18.0, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Special K Cereal', 'Special K graanvlokken', 'Kellogg''s', 'supermarket', 'albert_heijn', NULL, 'granen', 30, '1 kop', 379, 6.8, 85.5, 0.9, 3.5, 4.5, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Choco Flakes', 'Chocolade vlokken', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'granen', 30, '1 kop', 400, 6.5, 80.0, 4.5, 2.5, 28.0, FALSE);

-- Rijst (6 products)
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('White Rice', 'Witte rijst', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'granen', 150, '1 bakje gekookt', 130, 2.7, 28.0, 0.3, 0.4, 0.1, TRUE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Brown Rice', 'Bruine rijst', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'granen', 150, '1 bakje gekookt', 131, 2.6, 27.5, 1.0, 1.5, 0.3, TRUE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Basmati Rice', 'Basmati rijst', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'granen', 150, '1 bakje gekookt', 130, 2.5, 28.5, 0.2, 0.3, 0.0, TRUE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Jasmine Rice', 'Jasmijn rijst', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'granen', 150, '1 bakje gekookt', 130, 2.6, 28.0, 0.3, 0.2, 0.2, TRUE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Wild Rice', 'Zilvervlies rijst', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'granen', 150, '1 bakje gekookt', 135, 4.3, 26.0, 0.4, 1.8, 0.1, TRUE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Arborio Risotto Rice', 'Arborio risotto rijst', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'granen', 150, '1 bakje gekookt', 135, 2.4, 31.0, 0.3, 0.5, 0.0, FALSE);

-- Pasta (7 products)
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Spaghetti', 'Spaghetti', 'Barilla', 'supermarket', 'albert_heijn', NULL, 'granen', 150, '1 bakje gekookt', 131, 5.3, 25.0, 1.1, 1.8, 0.5, TRUE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Penne', 'Penne', 'De Cecco', 'supermarket', 'albert_heijn', NULL, 'granen', 150, '1 bakje gekookt', 131, 5.3, 25.0, 1.1, 1.8, 0.5, TRUE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Macaroni', 'Macaroni', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'granen', 150, '1 bakje gekookt', 130, 5.0, 25.5, 1.0, 1.5, 0.3, TRUE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Whole Wheat Pasta', 'Volkoren pasta', 'Barilla', 'supermarket', 'albert_heijn', NULL, 'granen', 150, '1 bakje gekookt', 124, 6.5, 22.0, 1.2, 3.5, 0.4, TRUE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Fusilli Pasta', 'Fusilli pasta', 'Barilla', 'supermarket', 'albert_heijn', NULL, 'granen', 150, '1 bakje gekookt', 131, 5.3, 25.0, 1.1, 1.8, 0.5, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Farfalle Pasta', 'Farfalle pasta', 'De Cecco', 'supermarket', 'albert_heijn', NULL, 'granen', 150, '1 bakje gekookt', 131, 5.3, 25.0, 1.1, 1.8, 0.5, FALSE);

-- Couscous, bulgur, quinoa (3 products)
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Couscous', 'Couscous', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'granen', 150, '1 bakje gekookt', 112, 3.8, 23.0, 0.3, 1.5, 0.2, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Bulgur Wheat', 'Bulgur tarwe', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'granen', 150, '1 bakje gekookt', 108, 3.9, 19.5, 0.5, 4.5, 0.1, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Quinoa', 'Quinoa', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'granen', 150, '1 bakje gekookt', 120, 4.4, 21.3, 1.9, 2.8, 0.0, FALSE);

-- Noedels (3 products)
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Egg Noodles', 'Mie noedels', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'granen', 150, '1 bakje gekookt', 137, 5.0, 26.0, 1.3, 1.2, 0.2, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Ramen Noodles', 'Ramen noedels', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'granen', 150, '1 bakje gekookt', 135, 5.5, 25.0, 1.2, 1.0, 0.3, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Glass Noodles', 'Glasnoedels', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'granen', 150, '1 bakje gekookt', 99, 0.2, 24.5, 0.2, 0.0, 0.0, FALSE);

-- Overig granen (9 products)
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Pancake Mix', 'Pannenkoekenmix', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'granen', 50, '¼ kop', 354, 8.0, 73.0, 1.5, 1.0, 2.5, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Wheat Tortillas', 'Tarwe wraps', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'granen', 60, '1 wrap', 175, 4.7, 30.0, 3.5, 1.8, 1.5, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Whole Grain Wraps', 'Volkoren wraps', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'granen', 60, '1 wrap', 158, 5.5, 28.0, 2.5, 3.5, 0.8, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Buckwheat Groats', 'Boekweit groepen', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'granen', 150, '1 bakje gekookt', 92, 3.4, 20.0, 0.4, 1.7, 0.0, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Polenta', 'Polenta', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'granen', 150, '1 bakje gekookt', 101, 2.0, 21.0, 0.7, 1.5, 0.1, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Barley Grains', 'Gerste korrels', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'granen', 150, '1 bakje gekookt', 98, 2.3, 22.0, 0.4, 3.8, 0.0, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Farro Grains', 'Farro korrels', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'granen', 150, '1 bakje gekookt', 120, 3.6, 27.0, 0.7, 4.0, 0.0, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Millet Grains', 'Gierst korrels', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'granen', 150, '1 bakje gekookt', 118, 3.5, 23.0, 1.0, 2.3, 0.0, FALSE);

-- =====================================================================
-- BROOD (BREAD) - 30 PRODUCTS
-- =====================================================================

-- Standaard broodsoorten (8 products)
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('White Bread', 'Wit brood', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'brood', 40, '1 snee', 265, 8.5, 47.0, 3.0, 2.7, 4.5, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Brown Bread', 'Bruin brood', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'brood', 40, '1 snee', 239, 8.0, 42.0, 2.5, 3.5, 3.2, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Whole Grain Bread', 'Volkoren brood', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'brood', 40, '1 snee', 219, 8.5, 38.0, 2.8, 5.5, 2.5, TRUE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Multigrain Bread', 'Meergranen brood', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'brood', 40, '1 snee', 229, 8.8, 40.5, 2.9, 5.0, 3.0, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Tiger Bread', 'Tijgerbrood', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'brood', 40, '1 snee', 255, 8.2, 46.0, 2.8, 3.2, 3.8, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Rye Bread', 'Roggebrood', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'brood', 40, '1 snee', 215, 8.8, 38.5, 2.2, 5.8, 2.0, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Pumpernickel Bread', 'Pumpernickel', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'brood', 40, '1 snee', 212, 8.5, 40.5, 1.5, 6.0, 1.5, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Sourdough Bread', 'Zuurdesembrood', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'brood', 40, '1 snee', 245, 8.0, 44.0, 2.5, 2.5, 1.5, FALSE);

-- Crackers en knäckebröd (5 products)
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Wasa Crispbread', 'Wasa knäckebröd', 'Wasa', 'supermarket', 'albert_heijn', NULL, 'brood', 10, '1 cracker', 321, 9.0, 63.0, 1.5, 7.0, 2.5, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('LU Cracotte Crackers', 'LU Cracotte crackers', 'LU', 'supermarket', 'albert_heijn', NULL, 'brood', 9, '1 cracker', 387, 7.5, 73.0, 7.0, 2.5, 2.0, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Rice Crackers', 'Rijstwafels', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'brood', 8, '1 wafel', 380, 6.0, 80.0, 2.5, 1.0, 0.0, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Knäckebröd Wholegrain', 'Knäckebröd volkoren', 'Wasa', 'supermarket', 'albert_heijn', NULL, 'brood', 10, '1 cracker', 315, 10.0, 60.0, 2.0, 8.5, 1.5, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Melba Toast', 'Melba toast', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'brood', 5, '1 snee', 387, 8.5, 76.0, 2.0, 3.0, 1.5, FALSE);

-- Beschuit, biscuits en speciaal brood (5 products)
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Beschuit', 'Beschuit', 'Bolletje', 'supermarket', 'albert_heijn', NULL, 'brood', 6, '1 beschuit', 393, 7.5, 77.5, 2.5, 2.5, 2.0, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Pita Bread', 'Pita brood', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'brood', 60, '1 pita', 265, 8.0, 48.0, 1.2, 1.5, 3.5, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Turkish Bread', 'Turks brood', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'brood', 60, '1 stuk', 290, 8.5, 50.0, 3.5, 2.0, 4.0, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Naan Bread', 'Naan brood', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'brood', 80, '1 naan', 262, 6.8, 35.0, 8.8, 1.0, 1.5, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Focaccia Bread', 'Focaccia brood', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'brood', 50, '1 stuk', 285, 7.5, 35.0, 10.0, 1.2, 2.0, FALSE);

-- Bagels, croissants, rollades (5 products)
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Bagel Plain', 'Bagel naturel', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'brood', 85, '1 bagel', 245, 9.0, 48.0, 1.5, 2.5, 4.5, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Croissant Butter', 'Botercroisssant', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'brood', 60, '1 croissant', 406, 8.0, 38.0, 20.0, 2.0, 8.5, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Croissant Chocolate', 'Chocoladecroisssant', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'brood', 65, '1 croissant', 410, 7.5, 43.0, 20.5, 1.8, 14.0, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Pain au Chocolat', 'Pain au chocolat', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'brood', 60, '1 stuk', 395, 6.5, 42.0, 19.0, 1.5, 13.5, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Brioche Bread', 'Brioche brood', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'brood', 50, '1 snee', 325, 6.5, 40.0, 15.0, 1.0, 10.5, FALSE);

-- AH Broodjes en andere (7 products)
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Puntbroodje', 'Puntbroodje AH', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'brood', 50, '1 broodje', 270, 8.5, 46.0, 3.5, 2.0, 3.5, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Ciabatta Roll', 'Ciabatta broodje', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'brood', 75, '1 broodje', 290, 9.0, 50.0, 3.8, 2.2, 2.5, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Pistolet', 'Pistolet broodje', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'brood', 40, '1 broodje', 260, 8.0, 46.5, 2.5, 1.8, 3.0, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Foccacia Roll', 'Foccacia broodje', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'brood', 60, '1 broodje', 280, 7.8, 38.0, 9.5, 1.5, 2.0, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Ontbijtkoek', 'Ontbijtkoek', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'brood', 40, '1 snee', 308, 5.5, 62.0, 3.0, 1.5, 22.5, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Woven Wrap Bread', 'Geweven brood wrap', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'brood', 50, '1 wrap', 245, 8.5, 42.0, 2.5, 2.0, 1.0, FALSE);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Gluten-Free Bread', 'Glutenvrij brood', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'brood', 40, '1 snee', 260, 4.0, 48.0, 3.0, 3.0, 2.5, FALSE);
