-- MŌVE Fitness Coaching App - Dutch/Belgian Food Products
-- Generated for: snacks, dranken (drinks), saus, and sports_nutrition categories

-- SNACKS (50 products)

INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES
('Lay''s Natural Chips', 'Lay''s Naturel Chips', 'Lay''s', 'supermarket', 'albert_heijn', NULL, 'snack', 28, '1 zakje (28g)', 536, 6, 51, 32, 5, 1, TRUE),
('Lay''s Paprika Chips', 'Lay''s Paprika Chips', 'Lay''s', 'supermarket', 'albert_heijn', NULL, 'snack', 28, '1 zakje (28g)', 536, 6, 51, 32, 5, 2, TRUE),
('Pringles Original', 'Pringles Origineel', 'Pringles', 'supermarket', 'albert_heijn', NULL, 'snack', 19, '1 portie (19g)', 509, 6, 48, 30, 4, 1, TRUE),
('Pringles Paprika', 'Pringles Paprika', 'Pringles', 'supermarket', 'albert_heijn', NULL, 'snack', 19, '1 portie (19g)', 509, 6, 48, 30, 4, 2, TRUE),
('Doritos Nacho Cheese', 'Doritos Nacho Cheese', 'Doritos', 'supermarket', 'albert_heijn', NULL, 'snack', 28, '1 zakje (28g)', 541, 7, 50, 32, 5, 1, TRUE),
('Tortilla Chips Zout', 'Tortilla Chips Zout', 'AH', 'supermarket', 'albert_heijn', NULL, 'snack', 30, '1 handvol (30g)', 498, 7, 53, 28, 6, 1, FALSE),
('Borrelnootjes Mix', 'Borrelnootjes Mix', 'AH', 'supermarket', 'albert_heijn', NULL, 'snack', 25, '1 handvol (25g)', 589, 17, 20, 50, 3, 4, FALSE),
('Cashews Gezouten', 'Cashews Gezouten', 'Jumbo', 'supermarket', 'albert_heijn', NULL, 'snack', 30, '1 handvol (30g)', 553, 16, 30, 44, 3, 5, FALSE),
('Pinda''s Gezouten', 'Pinda''s Gezouten', 'AH', 'supermarket', 'albert_heijn', NULL, 'snack', 30, '1 handvol (30g)', 567, 26, 20, 50, 2, 3, FALSE),
('Almonds Geroosterd', 'Amandelen Geroosterd', 'AH', 'supermarket', 'albert_heijn', NULL, 'snack', 28, '1 handvol (28g)', 579, 21, 22, 50, 3, 5, FALSE),
('Milka Chocolate 100g', 'Milka Melkchocolade 100g', 'Milka', 'supermarket', 'albert_heijn', NULL, 'snack', 30, '1 reep (30g)', 535, 8, 56, 30, 1, 53, FALSE),
('Tony''s Chocolonely Dark 70%', 'Tony''s Chocolonely Donker 70%', 'Tony''s Chocolonely', 'supermarket', 'albert_heijn', NULL, 'snack', 30, '1 reep (30g)', 602, 10, 33, 49, 6, 20, FALSE),
('KitKat 4 Finger', 'KitKat 4 Finger', 'Nestlé', 'supermarket', 'albert_heijn', NULL, 'snack', 22, '1 reep (22g)', 520, 6, 59, 28, 1, 45, FALSE),
('Mars Bar', 'Mars Reep', 'Mars', 'supermarket', 'albert_heijn', NULL, 'snack', 33, '1 reep (33g)', 526, 4, 68, 21, 1, 47, FALSE),
('Snickers Bar', 'Snickers Reep', 'Mars', 'supermarket', 'albert_heijn', NULL, 'snack', 33, '1 reep (33g)', 506, 11, 61, 24, 1, 44, TRUE),
('Twix Bar', 'Twix Reep', 'Mars', 'supermarket', 'albert_heijn', NULL, 'snack', 25, '1 reep (25g)', 517, 4, 63, 25, 1, 43, FALSE),
('Bounty Bar', 'Bounty Reep', 'Mars', 'supermarket', 'albert_heijn', NULL, 'snack', 29, '1 reep (29g)', 471, 3, 57, 24, 1, 43, FALSE),
('M&M''s Peanut', 'M&M''s Peanut', 'Mars', 'supermarket', 'albert_heijn', NULL, 'snack', 45, '1 zak (45g)', 503, 13, 57, 23, 2, 50, TRUE),
('Stroopwafel', 'Stroopwafel', 'Daelmans', 'supermarket', 'albert_heijn', NULL, 'snack', 17, '1 wafel (17g)', 407, 3, 72, 9, 1, 40, FALSE),
('Speculaas', 'Speculaas', 'Lotus', 'supermarket', 'albert_heijn', NULL, 'snack', 20, '2 koekjes (20g)', 471, 5, 65, 20, 1, 28, FALSE),
('Oreo Cookies', 'Oreo Koekjes', 'Mondelēz', 'supermarket', 'albert_heijn', NULL, 'snack', 34, '3 koekjes (34g)', 486, 4, 71, 21, 1, 38, FALSE),
('Digestive Biscuits', 'Digestive Koekjes', 'McVitie''s', 'supermarket', 'albert_heijn', NULL, 'snack', 30, '2 koekjes (30g)', 475, 7, 64, 20, 2, 15, FALSE),
('Bastogne Koekjes', 'Bastogne Koekjes', 'Lotus', 'supermarket', 'albert_heijn', NULL, 'snack', 22, '3 koekjes (22g)', 445, 6, 63, 18, 1, 25, FALSE),
('Gevulde Koek', 'Gevulde Koek', 'AH', 'supermarket', 'albert_heijn', NULL, 'snack', 35, '1 koek (35g)', 369, 4, 63, 10, 2, 35, FALSE),
('Ontbijtkoek', 'Ontbijtkoek', 'AH', 'supermarket', 'albert_heijn', NULL, 'snack', 40, '2 sneden (40g)', 291, 4, 63, 2, 2, 30, FALSE),
('Appelflap', 'Appelflap', 'AH', 'supermarket', 'albert_heijn', NULL, 'snack', 100, '1 appelflap (100g)', 287, 3, 45, 9, 2, 20, FALSE),
('Saucijzenbroodje', 'Saucijzenbroodje', 'AH', 'supermarket', 'albert_heijn', NULL, 'snack', 60, '1 broodje (60g)', 334, 12, 32, 16, 1, 3, FALSE),
('Kaasbroodje', 'Kaasbroodje', 'AH', 'supermarket', 'albert_heijn', NULL, 'snack', 60, '1 broodje (60g)', 321, 14, 30, 14, 1, 2, FALSE),
('Popcorn Zout', 'Popcorn Zout', 'AH', 'supermarket', 'albert_heijn', NULL, 'snack', 20, '1 handvol (20g)', 375, 12, 55, 9, 8, 0, FALSE),
('Popcorn Zoet', 'Popcorn Zoet', 'AH', 'supermarket', 'albert_heijn', NULL, 'snack', 20, '1 handvol (20g)', 410, 8, 65, 12, 6, 35, FALSE),
('Popcorn Gekaramelliseerd', 'Popcorn Gekaramelliseerd', 'AH', 'supermarket', 'albert_heijn', NULL, 'snack', 25, '1 zakje (25g)', 428, 6, 72, 13, 3, 45, FALSE),
('Rijstwafels Met Melkchocolade', 'Rijstwafels Met Melkchocolade', 'AH', 'supermarket', 'albert_heijn', NULL, 'snack', 10, '1 wafel (10g)', 383, 4, 78, 5, 1, 35, FALSE),
('Nature Valley Oats & Honey', 'Nature Valley Haver & Honing', 'Nature Valley', 'supermarket', 'albert_heijn', NULL, 'snack', 42, '1 reep (42g)', 405, 9, 63, 14, 5, 30, FALSE),
('Nakd Cocoa Orange', 'Nakd Cacao Orange', 'Nakd', 'supermarket', 'albert_heijn', NULL, 'snack', 35, '1 reep (35g)', 379, 9, 55, 12, 5, 28, FALSE),
('Trek Peanut & Choco', 'Trek Pinda & Choco', 'Trek', 'supermarket', 'albert_heijn', NULL, 'snack', 50, '1 reep (50g)', 444, 14, 51, 18, 5, 29, FALSE),
('Venco Drop Assortiment', 'Venco Drop Assortiment', 'Venco', 'supermarket', 'albert_heijn', NULL, 'snack', 30, '1 handvol (30g)', 319, 0, 82, 0, 0, 42, FALSE),
('Klene Zoethout', 'Klene Zoethout', 'Klene', 'supermarket', 'albert_heijn', NULL, 'snack', 25, '1 handvol (25g)', 311, 0, 80, 0, 0, 40, FALSE),
('Magnum Almond', 'Magnum Almond IJsje', 'Magnum', 'supermarket', 'albert_heijn', NULL, 'snack', 100, '1 ijsje (100g)', 268, 5, 26, 16, 2, 22, FALSE),
('Cornetto Original', 'Cornetto Origineel', 'Unilever', 'supermarket', 'albert_heijn', NULL, 'snack', 90, '1 ijsje (90g)', 224, 3, 27, 11, 1, 24, FALSE),
('Ben & Jerry''s Vanilla', 'Ben & Jerry''s Vanilla', 'Ben & Jerry''s', 'supermarket', 'albert_heijn', NULL, 'snack', 100, '100ml IJsroom', 207, 3, 22, 11, 0, 20, FALSE),
('Luikse Wafel', 'Luikse Wafel', 'AH', 'supermarket', 'albert_heijn', NULL, 'snack', 45, '1 wafel (45g)', 325, 5, 56, 8, 1, 28, FALSE),
('Merci Chocolates', 'Merci Chocoladeassortiment', 'Storck', 'supermarket', 'albert_heijn', NULL, 'snack', 10, '1 bonbon (10g)', 486, 4, 65, 21, 1, 50, FALSE),
('Lindor Truffles', 'Lindor Truffles', 'Lindor', 'supermarket', 'albert_heijn', NULL, 'snack', 15, '1 truffle (15g)', 520, 4, 52, 32, 1, 45, FALSE),
('Haribo Gummy Bears', 'Haribo Gummibeertjes', 'Haribo', 'supermarket', 'albert_heijn', NULL, 'snack', 20, '1 zakje (20g)', 343, 6, 76, 0, 0, 48, FALSE),
('Campina Yoghurt Muesli', 'Campina Yoghurt Muesli', 'Campina', 'supermarket', 'albert_heijn', NULL, 'snack', 150, '1 bakje (150g)', 120, 4, 19, 2, 2, 14, FALSE),
('Nutella', 'Nutella', 'Ferrero', 'supermarket', 'albert_heijn', NULL, 'snack', 15, '1 portiepak (15g)', 539, 6, 63, 31, 1, 56, FALSE),
('Pindakaas', 'Pindakaas', 'AH', 'supermarket', 'albert_heijn', NULL, 'snack', 32, '2 lepels (32g)', 590, 24, 20, 50, 4, 6, FALSE),
('Granola Bar Honey', 'Granola Reep Honing', 'AH', 'supermarket', 'albert_heijn', NULL, 'snack', 40, '1 reep (40g)', 445, 8, 60, 18, 3, 32, FALSE);

-- DRANKEN (50 products)

INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES
('Heineken Beer', 'Heineken Bier', 'Heineken', 'supermarket', 'albert_heijn', NULL, 'dranken', 100, '100ml bier', 42, 0.4, 3, 0, 0, 0, TRUE),
('Jupiler Beer', 'Jupiler Bier', 'Jupiler', 'supermarket', 'albert_heijn', NULL, 'dranken', 100, '100ml bier', 43, 0.5, 3.2, 0, 0, 0, TRUE),
('Duvel Golden Ale', 'Duvel Blond Bier', 'Duvel', 'supermarket', 'albert_heijn', NULL, 'dranken', 100, '100ml bier', 62, 0.5, 6.5, 0, 0, 0, FALSE),
('Leffe Blonde', 'Leffe Blond', 'Leffe', 'supermarket', 'albert_heijn', NULL, 'dranken', 100, '100ml bier', 54, 0.4, 5.5, 0, 0, 0, FALSE),
('Westmalle Trappist', 'Westmalle Trappist', 'Westmalle', 'supermarket', 'albert_heijn', NULL, 'dranken', 100, '100ml bier', 67, 0.6, 7, 0, 0, 0, FALSE),
('Palm Beer', 'Palm Bier', 'Palm', 'supermarket', 'albert_heijn', NULL, 'dranken', 100, '100ml bier', 45, 0.4, 3.5, 0, 0, 0, FALSE),
('Stella Artois', 'Stella Artois Bier', 'Stella Artois', 'supermarket', 'albert_heijn', NULL, 'dranken', 100, '100ml bier', 48, 0.4, 4, 0, 0, 0, TRUE),
('Coca-Cola', 'Coca-Cola', 'Coca-Cola', 'supermarket', 'albert_heijn', NULL, 'dranken', 100, '100ml frisdrank', 42, 0, 10.6, 0, 0, 10.6, TRUE),
('Coca-Cola Zero', 'Coca-Cola Zero', 'Coca-Cola', 'supermarket', 'albert_heijn', NULL, 'dranken', 100, '100ml frisdrank', 0.4, 0, 0.1, 0, 0, 0, TRUE),
('Fanta Orange', 'Fanta Sinaasappel', 'Fanta', 'supermarket', 'albert_heijn', NULL, 'dranken', 100, '100ml frisdrank', 45, 0, 11, 0, 0, 11, FALSE),
('Sprite', 'Sprite', 'Sprite', 'supermarket', 'albert_heijn', NULL, 'dranken', 100, '100ml frisdrank', 42, 0, 10.3, 0, 0, 10.3, FALSE),
('7Up', '7Up', '7Up', 'supermarket', 'albert_heijn', NULL, 'dranken', 100, '100ml frisdrank', 42, 0, 10.3, 0, 0, 10.3, FALSE),
('Ice Tea Peach', 'Ice Tea Perzik', 'Nestlé', 'supermarket', 'albert_heijn', NULL, 'dranken', 100, '100ml Ice Tea', 30, 0, 7.5, 0, 0, 7.5, FALSE),
('Sinaasappelsap', 'Sinaasappelsap', 'AH', 'supermarket', 'albert_heijn', NULL, 'dranken', 100, '100ml sap', 43, 0.7, 10.4, 0.1, 0.1, 9, FALSE),
('Appelsap', 'Appelsap', 'AH', 'supermarket', 'albert_heijn', NULL, 'dranken', 100, '100ml sap', 46, 0.3, 11, 0.1, 0.1, 10, FALSE),
('Tomatensap', 'Tomatensap', 'AH', 'supermarket', 'albert_heijn', NULL, 'dranken', 100, '100ml sap', 17, 0.9, 3.5, 0.1, 0.8, 2, FALSE),
('Multivitamine Sap', 'Multivitamine Sap', 'AH', 'supermarket', 'albert_heijn', NULL, 'dranken', 100, '100ml sap', 50, 0.5, 12, 0.1, 0, 11, FALSE),
('Koffie Zwart', 'Koffie Zwart', 'AH', 'supermarket', 'albert_heijn', NULL, 'dranken', 100, '100ml koffie', 2, 0.2, 0.3, 0, 0, 0, FALSE),
('Cappuccino', 'Cappuccino', 'Nescafé', 'supermarket', 'albert_heijn', NULL, 'dranken', 100, '100ml cappuccino', 58, 2, 8, 2.5, 0, 7, FALSE),
('Latte Coffee', 'Latte Koffie', 'AH', 'supermarket', 'albert_heijn', NULL, 'dranken', 100, '100ml latte', 64, 3.3, 5, 3.5, 0, 5, FALSE),
('Thee Zwart', 'Thee Zwart', 'AH', 'supermarket', 'albert_heijn', NULL, 'dranken', 100, '100ml thee', 2, 0.1, 0.5, 0, 0, 0, FALSE),
('Red Bull Energy', 'Red Bull Energiedrank', 'Red Bull', 'supermarket', 'albert_heijn', NULL, 'dranken', 100, '100ml energiedrank', 53, 0, 13, 0, 0, 12, FALSE),
('Monster Energy', 'Monster Energiedrank', 'Monster', 'supermarket', 'albert_heijn', NULL, 'dranken', 100, '100ml energiedrank', 49, 0.1, 12, 0, 0, 12, FALSE),
('Water Plat', 'Water Plat', 'AH', 'supermarket', 'albert_heijn', NULL, 'dranken', 100, '100ml water', 0, 0, 0, 0, 0, 0, FALSE),
('Water Bruisend', 'Water Bruisend', 'AH', 'supermarket', 'albert_heijn', NULL, 'dranken', 100, '100ml water', 0, 0, 0, 0, 0, 0, FALSE),
('Chocomel', 'Chocomel', 'Friesland Campina', 'supermarket', 'albert_heijn', NULL, 'dranken', 100, '100ml chocomel', 70, 3.1, 11, 2.3, 0, 10, FALSE),
('Fristi', 'Fristi', 'Friesland Campina', 'supermarket', 'albert_heijn', NULL, 'dranken', 100, '100ml fristi', 63, 1, 11, 2, 0, 10, FALSE),
('Innocent Smoothie Mango', 'Innocent Smoothie Mango', 'Innocent', 'supermarket', 'albert_heijn', NULL, 'dranken', 100, '100ml smoothie', 56, 0.3, 13, 0.1, 1, 11, FALSE),
('Aquarius Sports Drink', 'Aquarius Sportdrank', 'Aquarius', 'supermarket', 'albert_heijn', NULL, 'dranken', 100, '100ml sportdrank', 30, 0, 7.3, 0, 0, 7, FALSE),
('AA Drink Orange', 'AA Drink Oranje', 'AA Drink', 'supermarket', 'albert_heijn', NULL, 'dranken', 100, '100ml sportdrank', 32, 0.1, 7.5, 0, 0, 7, FALSE),
('Gatorade Orange', 'Gatorade Oranje', 'Gatorade', 'supermarket', 'albert_heijn', NULL, 'dranken', 100, '100ml sportdrank', 31, 0.1, 7.5, 0, 0, 7, FALSE),
('Limonade', 'Limonade', 'AH', 'supermarket', 'albert_heijn', NULL, 'dranken', 100, '100ml limonade', 40, 0, 10, 0, 0, 10, FALSE),
('Karvan Cévitam Siroop', 'Karvan Cévitam Siroop', 'Karvan Cévitam', 'supermarket', 'albert_heijn', NULL, 'dranken', 100, '100ml siroop (geconcentreerd)', 288, 0, 72, 0, 0, 72, FALSE),
('Havermelk', 'Havermelk', 'Alpro', 'supermarket', 'albert_heijn', NULL, 'dranken', 100, '100ml havermelk', 48, 1, 6, 1.5, 0.5, 2, FALSE),
('Amandelmelk', 'Amandelmelk', 'Alpro', 'supermarket', 'albert_heijn', NULL, 'dranken', 100, '100ml amandelmelk', 32, 1.1, 1.3, 2.5, 0.4, 0.1, FALSE),
('Sojamelk', 'Sojamelk', 'Alpro', 'supermarket', 'albert_heijn', NULL, 'dranken', 100, '100ml sojamelk', 49, 3.6, 2, 1.9, 0.5, 0.1, FALSE),
('Kokosmelk', 'Kokosmelk', 'Aroy-D', 'supermarket', 'albert_heijn', NULL, 'dranken', 100, '100ml kokosmelk', 67, 0.7, 3.3, 5.5, 0, 0, FALSE),
('Rood Wijn', 'Rode Wijn', 'AH', 'supermarket', 'albert_heijn', NULL, 'dranken', 100, '100ml rode wijn', 70, 0, 2.6, 0, 0, 0.3, FALSE),
('Wit Wijn', 'Witte Wijn', 'AH', 'supermarket', 'albert_heijn', NULL, 'dranken', 100, '100ml witte wijn', 66, 0, 0.6, 0, 0, 1, FALSE),
('Rosé Wijn', 'Rosé Wijn', 'AH', 'supermarket', 'albert_heijn', NULL, 'dranken', 100, '100ml rosé wijn', 68, 0, 1.5, 0, 0, 2, FALSE),
('Jus d''Orange Vers', 'Vers Sinaasappelsap', 'AH', 'supermarket', 'albert_heijn', NULL, 'dranken', 100, '100ml vers sap', 45, 0.8, 11, 0.1, 0.1, 9, FALSE),
('Kombucha', 'Kombucha', 'Remedy', 'supermarket', 'albert_heijn', NULL, 'dranken', 100, '100ml kombucha', 24, 0, 4, 0, 0, 3, FALSE),
('Matcha Thee', 'Matcha Thee', 'AH', 'supermarket', 'albert_heijn', NULL, 'dranken', 100, '100ml matcha thee', 3, 0.1, 0.5, 0, 0, 0, FALSE),
('Espresso', 'Espresso', 'AH', 'supermarket', 'albert_heijn', NULL, 'dranken', 100, '100ml espresso', 3, 0.2, 0.4, 0, 0, 0, FALSE),
('Melkshake Vanille', 'Milkshake Vanille', 'AH', 'supermarket', 'albert_heijn', NULL, 'dranken', 100, '100ml milkshake', 68, 3.2, 9, 2.8, 0, 8, FALSE),
('Melkshake Aardbei', 'Milkshake Aardbei', 'AH', 'supermarket', 'albert_heijn', NULL, 'dranken', 100, '100ml milkshake', 65, 3, 10, 2.5, 0, 9, FALSE),
('Chocolademelk', 'Chocolademelk', 'AH', 'supermarket', 'albert_heijn', NULL, 'dranken', 100, '100ml chocolademelk', 72, 3.5, 10, 3, 0, 9, FALSE);

-- SAUS (20 products)

INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES
('Heinz Ketchup', 'Heinz Ketchup', 'Heinz', 'supermarket', 'albert_heijn', NULL, 'saus', 15, '1 eetlepel (15g)', 109, 1.2, 25, 0.1, 0.3, 23, FALSE),
('Hellmann''s Mayonaise', 'Hellmann''s Mayonaise', 'Hellmann''s', 'supermarket', 'albert_heijn', NULL, 'saus', 15, '1 eetlepel (15g)', 717, 0.1, 0.6, 80, 0, 0, FALSE),
('Calvé Mayonaise', 'Calvé Mayonaise', 'Calvé', 'supermarket', 'albert_heijn', NULL, 'saus', 15, '1 eetlepel (15g)', 710, 0, 0.5, 79, 0, 0, FALSE),
('Curry Saus', 'Curry Saus', 'AH', 'supermarket', 'albert_heijn', NULL, 'saus', 15, '1 eetlepel (15g)', 153, 1, 7, 13, 0, 4, FALSE),
('BBQ Saus', 'BBQ Saus', 'AH', 'supermarket', 'albert_heijn', NULL, 'saus', 20, '1.5 eetlepel (20g)', 131, 0.5, 25, 2, 0.5, 22, FALSE),
('Sweet Chili Saus', 'Sweet Chili Saus', 'AH', 'supermarket', 'albert_heijn', NULL, 'saus', 15, '1 eetlepel (15g)', 132, 0.3, 32, 0.1, 0, 31, FALSE),
('Pesto Groen', 'Pesto Groen', 'AH', 'supermarket', 'albert_heijn', NULL, 'saus', 10, '1 eetlepel (10g)', 361, 7, 3, 37, 1, 0.5, FALSE),
('Pesto Rood', 'Pesto Rood', 'AH', 'supermarket', 'albert_heijn', NULL, 'saus', 10, '1 eetlepel (10g)', 345, 5, 4, 35, 1, 2, FALSE),
('Hummus Naturel', 'Hummus Naturel', 'AH', 'supermarket', 'albert_heijn', NULL, 'saus', 30, '3 eetlepels (30g)', 159, 4.8, 14, 8.5, 2.5, 0.7, FALSE),
('Hummus Rode Biet', 'Hummus Rode Biet', 'AH', 'supermarket', 'albert_heijn', NULL, 'saus', 30, '3 eetlepels (30g)', 142, 4, 15, 6.5, 2, 3, FALSE),
('Tzatziki', 'Tzatziki', 'AH', 'supermarket', 'albert_heijn', NULL, 'saus', 30, '3 eetlepels (30g)', 65, 2.5, 2, 4.5, 0, 1, FALSE),
('Guacamole', 'Guacamole', 'AH', 'supermarket', 'albert_heijn', NULL, 'saus', 30, '3 eetlepels (30g)', 193, 1.5, 5, 19, 2, 0.5, FALSE),
('Tomatensaus Bertolli', 'Tomatensaus Bertolli', 'Bertolli', 'supermarket', 'albert_heijn', NULL, 'saus', 100, '1 potje (100g)', 42, 1.5, 8, 0.5, 1.5, 6, FALSE),
('Pastasaus Classico', 'Pastasaus Classico', 'Classico', 'supermarket', 'albert_heijn', NULL, 'saus', 100, '1 portie (100g)', 51, 1.2, 9, 1.5, 1, 7, FALSE),
('Olijfolie Dressing', 'Olijfolie Dressing', 'AH', 'supermarket', 'albert_heijn', NULL, 'saus', 15, '1 eetlepel (15g)', 678, 0, 2, 75, 0, 0, FALSE),
('Vinaigrette', 'Vinaigrette', 'AH', 'supermarket', 'albert_heijn', NULL, 'saus', 15, '1 eetlepel (15g)', 304, 0.3, 2, 32, 0, 1, FALSE),
('Sojasaus Kikkoman', 'Sojasaus Kikkoman', 'Kikkoman', 'supermarket', 'albert_heijn', NULL, 'saus', 15, '1 eetlepel (15g)', 71, 10, 5, 0.3, 0, 3, FALSE),
('Oestersaus', 'Oestersaus', 'AH', 'supermarket', 'albert_heijn', NULL, 'saus', 15, '1 eetlepel (15g)', 64, 6.5, 7, 0.5, 0, 4, FALSE),
('Sambal Oelek', 'Sambal Oelek', 'AH', 'supermarket', 'albert_heijn', NULL, 'saus', 5, '1 theelepel (5g)', 88, 2.5, 10, 4, 1.5, 3, FALSE),
('Sriracha Hot Sauce', 'Sriracha Hete Saus', 'Tabasco', 'supermarket', 'albert_heijn', NULL, 'saus', 5, '1 theelepel (5g)', 106, 1.5, 15, 4, 0, 8, FALSE);

-- SPORTS NUTRITION (50 products)

-- Upfront Nutrition (15)
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES
('Upfront Protein Bar Chocolate', 'Upfront Protein Reep Chocolade', 'upfront_nutrition', 'sports_nutrition', 'upfront_nutrition', NULL, 'supplement', 50, '1 reep (50g)', 383, 42, 35, 8, 15, 2, TRUE),
('Upfront Protein Bar Peanut Butter', 'Upfront Protein Reep Pindakaas', 'upfront_nutrition', 'sports_nutrition', 'upfront_nutrition', NULL, 'supplement', 50, '1 reep (50g)', 389, 40, 36, 10, 14, 3, FALSE),
('Upfront Protein Bar Vanilla', 'Upfront Protein Reep Vanille', 'upfront_nutrition', 'sports_nutrition', 'upfront_nutrition', NULL, 'supplement', 50, '1 reep (50g)', 381, 41, 37, 7, 13, 2, FALSE),
('Upfront Protein Cookies', 'Upfront Protein Koekjes', 'upfront_nutrition', 'sports_nutrition', 'upfront_nutrition', NULL, 'supplement', 40, '2 koekjes (40g)', 387, 38, 40, 9, 12, 4, FALSE),
('Upfront Ready Shake Vanilla', 'Upfront Ready Shake Vanille', 'upfront_nutrition', 'sports_nutrition', 'upfront_nutrition', NULL, 'supplement', 250, '1 shake (250ml)', 108, 20, 9, 1.5, 0, 3, FALSE),
('Upfront Ready Shake Chocolate', 'Upfront Ready Shake Chocolade', 'upfront_nutrition', 'sports_nutrition', 'upfront_nutrition', NULL, 'supplement', 250, '1 shake (250ml)', 112, 21, 10, 1.5, 0, 4, FALSE),
('Upfront Protein Chips Salt Vinegar', 'Upfront Protein Chips Zout Azijn', 'upfront_nutrition', 'sports_nutrition', 'upfront_nutrition', NULL, 'supplement', 40, '1 zakje (40g)', 421, 36, 38, 12, 10, 2, FALSE),
('Upfront Protein Bread', 'Upfront Protein Brood', 'upfront_nutrition', 'sports_nutrition', 'upfront_nutrition', NULL, 'supplement', 50, '1 snede (50g)', 276, 38, 24, 6, 8, 3, FALSE),
('Upfront Pre-Workout Energy', 'Upfront Pre-Workout', 'upfront_nutrition', 'sports_nutrition', 'upfront_nutrition', NULL, 'supplement', 100, '1 portie (100g poeder)', 372, 2, 92, 0.5, 0, 85, FALSE),
('Upfront Creatine Monohydrate', 'Upfront Creatine', 'upfront_nutrition', 'sports_nutrition', 'upfront_nutrition', NULL, 'supplement', 100, '1 portie (5g)', 0, 0, 0, 0, 0, 0, FALSE),
('Upfront BCAA Amino Acids', 'Upfront BCAA Aminozuren', 'upfront_nutrition', 'sports_nutrition', 'upfront_nutrition', NULL, 'supplement', 100, '1 portie', 389, 100, 0, 0, 0, 0, FALSE),
('Upfront High Protein Bowl Chicken', 'Upfront High Protein Kom Kip', 'upfront_nutrition', 'sports_nutrition', 'upfront_nutrition', NULL, 'supplement', 400, '1 kom (400g)', 125, 25, 12, 1.5, 3, 2, FALSE),
('Upfront Omega-3 Fish Oil', 'Upfront Omega-3 Visolie', 'upfront_nutrition', 'sports_nutrition', 'upfront_nutrition', NULL, 'supplement', 100, '1 portie (4 capsules)', 900, 0, 0, 100, 0, 0, FALSE),
('Upfront Multivitamin', 'Upfront Multivitamine', 'upfront_nutrition', 'sports_nutrition', 'upfront_nutrition', NULL, 'supplement', 1, '1 tablet', 370, 0, 92, 0, 0, 0, FALSE),
('Upfront Whey Protein Isolate', 'Upfront Whey Protein Isolaat', 'upfront_nutrition', 'sports_nutrition', 'upfront_nutrition', NULL, 'supplement', 100, '1 scoop (30g)', 365, 90, 3, 2, 0, 0.5, FALSE),

-- ESN (15)
('ESN Designer Whey Vanilla', 'ESN Designer Whey Vanille', 'esn', 'sports_nutrition', 'esn', NULL, 'supplement', 100, '1 scoop (30g)', 368, 88, 4, 3, 0, 1, TRUE),
('ESN Designer Whey Chocolate', 'ESN Designer Whey Chocolade', 'esn', 'sports_nutrition', 'esn', NULL, 'supplement', 100, '1 scoop (30g)', 368, 88, 4, 3, 0, 1, TRUE),
('ESN Designer Whey Strawberry', 'ESN Designer Whey Aardbei', 'esn', 'sports_nutrition', 'esn', NULL, 'supplement', 100, '1 scoop (30g)', 368, 88, 4, 3, 0, 1, FALSE),
('ESN Designer Whey Cookies Cream', 'ESN Designer Whey Cookies & Cream', 'esn', 'sports_nutrition', 'esn', NULL, 'supplement', 100, '1 scoop (30g)', 368, 88, 5, 3, 0, 2, FALSE),
('ESN Designer Whey Banana', 'ESN Designer Whey Banaan', 'esn', 'sports_nutrition', 'esn', NULL, 'supplement', 100, '1 scoop (30g)', 368, 88, 5, 3, 0, 2, FALSE),
('ESN Isoclear Whey Berry', 'ESN Isoclear Whey Bes', 'esn', 'sports_nutrition', 'esn', NULL, 'supplement', 100, '1 scoop (30g)', 365, 90, 2, 1.5, 0, 0.5, FALSE),
('ESN Isoclear Whey Apple', 'ESN Isoclear Whey Appel', 'esn', 'sports_nutrition', 'esn', NULL, 'supplement', 100, '1 scoop (30g)', 365, 90, 2, 1.5, 0, 0.5, FALSE),
('ESN Casein Vanilla', 'ESN Casein Vanille', 'esn', 'sports_nutrition', 'esn', NULL, 'supplement', 100, '1 scoop (30g)', 365, 80, 8, 4, 0, 2, FALSE),
('ESN Casein Chocolate', 'ESN Casein Chocolade', 'esn', 'sports_nutrition', 'esn', NULL, 'supplement', 100, '1 scoop (30g)', 365, 80, 8, 4, 0, 2, FALSE),
('ESN Creatine Monohydrate', 'ESN Creatine Monohydraat', 'esn', 'sports_nutrition', 'esn', NULL, 'supplement', 100, '1 portie (5g)', 0, 0, 0, 0, 0, 0, FALSE),
('ESN EAA Amino Acids', 'ESN EAA Aminozuren', 'esn', 'sports_nutrition', 'esn', NULL, 'supplement', 100, '1 portie', 373, 99, 1, 0, 0, 0, FALSE),
('ESN BCAA Amino Acids', 'ESN BCAA Aminozuren', 'esn', 'sports_nutrition', 'esn', NULL, 'supplement', 100, '1 portie', 389, 100, 0, 0, 0, 0, FALSE),
('ESN Flexpresso Protein Coffee', 'ESN Flexpresso Proteine Koffie', 'esn', 'sports_nutrition', 'esn', NULL, 'supplement', 100, '200ml drank', 68, 20, 4, 1.5, 0, 2, FALSE),
('ESN Protein Dream Bar', 'ESN Protein Dream Reep', 'esn', 'sports_nutrition', 'esn', NULL, 'supplement', 50, '1 reep (50g)', 385, 44, 34, 10, 12, 3, FALSE),
('ESN Magnesium Citrate', 'ESN Magnesium Citraat', 'esn', 'sports_nutrition', 'esn', NULL, 'supplement', 100, '1 portie (3g)', 0, 0, 0.75, 0, 0, 0, FALSE),

-- Barebells (10)
('Barebells Salty Peanut', 'Barebells Zoute Pinda', 'barebells', 'sports_nutrition', 'barebells', NULL, 'supplement', 55, '1 reep (55g)', 395, 42, 25, 16, 14, 1, TRUE),
('Barebells Hazelnut Nougat', 'Barebells Hazelnoot Nougat', 'barebells', 'sports_nutrition', 'barebells', NULL, 'supplement', 55, '1 reep (55g)', 392, 41, 27, 14, 13, 2, TRUE),
('Barebells Caramel Cashew', 'Barebells Karamel Cashew', 'barebells', 'sports_nutrition', 'barebells', NULL, 'supplement', 55, '1 reep (55g)', 391, 40, 28, 15, 12, 3, TRUE),
('Barebells White Chocolate', 'Barebells Witte Chocolade', 'barebells', 'sports_nutrition', 'barebells', NULL, 'supplement', 55, '1 reep (55g)', 388, 42, 26, 14, 13, 4, TRUE),
('Barebells Cookies Cream', 'Barebells Cookies & Cream', 'barebells', 'sports_nutrition', 'barebells', NULL, 'supplement', 55, '1 reep (55g)', 390, 41, 27, 14, 12, 3, TRUE),
('Barebells Milkshake Strawberry', 'Barebells Milkshake Aardbei', 'barebells', 'sports_nutrition', 'barebells', NULL, 'supplement', 330, '1 fles (330ml)', 98, 20, 6, 1.5, 1, 2, FALSE),
('Barebells Milkshake Chocolate', 'Barebells Milkshake Chocolade', 'barebells', 'sports_nutrition', 'barebells', NULL, 'supplement', 330, '1 fles (330ml)', 102, 21, 7, 1.5, 1, 3, FALSE),
('Barebells Milkshake Vanilla', 'Barebells Milkshake Vanille', 'barebells', 'sports_nutrition', 'barebells', NULL, 'supplement', 330, '1 fles (330ml)', 100, 20, 6, 1.5, 1, 2, FALSE),
('Barebells Soft Bar Chocolate', 'Barebells Soft Reep Chocolade', 'barebells', 'sports_nutrition', 'barebells', NULL, 'supplement', 45, '1 reep (45g)', 348, 35, 35, 10, 8, 8, FALSE),
('Barebells Soft Bar Peanut', 'Barebells Soft Reep Pinda', 'barebells', 'sports_nutrition', 'barebells', NULL, 'supplement', 45, '1 reep (45g)', 352, 34, 36, 11, 7, 7, FALSE),

-- Other Brands (10)
('Quest Bar Chocolate Peanut', 'Quest Bar Chocolade Pinda', 'quest', 'sports_nutrition', 'quest', NULL, 'supplement', 60, '1 reep (60g)', 387, 40, 29, 11, 17, 1, FALSE),
('Grenade Carb Killa Chocolate', 'Grenade Carb Killa Chocolade', 'grenade', 'sports_nutrition', 'grenade', NULL, 'supplement', 60, '1 reep (60g)', 383, 40, 16, 14, 10, 1, FALSE),
('Optimum Nutrition Gold Standard Whey', 'Optimum Nutrition Gold Standard Whey', 'optimum_nutrition', 'sports_nutrition', 'optimum_nutrition', NULL, 'supplement', 100, '1 scoop (30g)', 370, 89, 3, 2, 0, 1, FALSE),
('MyProtein Impact Whey Chocolate', 'MyProtein Impact Whey Chocolade', 'myprotein', 'sports_nutrition', 'myprotein', NULL, 'supplement', 100, '1 scoop (25g)', 368, 88, 4, 2, 0, 0.5, FALSE),
('MyProtein Impact Whey Vanilla', 'MyProtein Impact Whey Vanille', 'myprotein', 'sports_nutrition', 'myprotein', NULL, 'supplement', 100, '1 scoop (25g)', 368, 88, 4, 2, 0, 0.5, FALSE),
('Nocco BCAA Tropical', 'Nocco BCAA Tropisch', 'nocco', 'sports_nutrition', 'nocco', NULL, 'supplement', 330, '1 blikje (330ml)', 12, 0, 3, 0, 0, 2, FALSE),
('Nocco BCAA Blood Orange', 'Nocco BCAA Bloed Oranje', 'nocco', 'sports_nutrition', 'nocco', NULL, 'supplement', 330, '1 blikje (330ml)', 12, 0, 3, 0, 0, 2, FALSE),
('Huel Shake Powder', 'Huel Shake Poeder', 'huel', 'sports_nutrition', 'huel', NULL, 'supplement', 100, '1 portie (38g)', 388, 30, 38, 13, 6, 1, FALSE),
('Huel Bar v3.0', 'Huel Reep v3.0', 'huel', 'sports_nutrition', 'huel', NULL, 'supplement', 65, '1 reep (65g)', 403, 33, 43, 15, 9, 4, FALSE),
('YFood Complete Nutrition Vanilla', 'YFood Volledige Voeding Vanille', 'yfood', 'sports_nutrition', 'yfood', NULL, 'supplement', 500, '1 fles (500ml)', 146, 25, 12, 3.5, 3, 2, FALSE);
