-- Meal Prep Bakkerij Seed File for Dutch/Belgian Fitness Coaching App
-- Realistic nutritional values per 100g

-- MEAL PREP STAPLES - GRANEN (Grains)
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Quinoa', 'Quinoa', 'Generic', 'supermarket', 'albert_heijn', NULL, 'granen', 100, '100g gekookt', 120, 4.4, 21.3, 1.9, 2.8, 0.6, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Couscous', 'Couscous', 'Generic', 'supermarket', 'albert_heijn', NULL, 'granen', 100, '100g gekookt', 112, 3.8, 23.2, 0.3, 1.5, 0.5, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Bulgur', 'Bulgur', 'Generic', 'supermarket', 'albert_heijn', NULL, 'granen', 100, '100g gekookt', 83, 3.1, 18.6, 0.2, 4.5, 0.4, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Polenta', 'Polenta', 'Generic', 'supermarket', 'albert_heijn', NULL, 'granen', 100, '100g gekookt', 133, 2.7, 28.1, 0.3, 1.7, 0.0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Buckwheat', 'Boekweit', 'Generic', 'supermarket', 'albert_heijn', NULL, 'granen', 100, '100g gekookt', 155, 6.0, 33.0, 1.0, 4.5, 0.0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Millet', 'Gierst', 'Generic', 'supermarket', 'albert_heijn', NULL, 'granen', 100, '100g gekookt', 119, 3.5, 23.7, 1.3, 2.3, 0.3, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Spelt', 'Spelt', 'Generic', 'supermarket', 'albert_heijn', NULL, 'granen', 100, '100g gekookt', 127, 5.7, 26.4, 1.1, 3.7, 0.4, false);

-- MEAL PREP STAPLES - LINZEN (Lentils)
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Red Lentils', 'Rode linzen', 'Generic', 'supermarket', 'albert_heijn', NULL, 'granen', 100, '100g gekookt', 116, 9.0, 20.0, 0.4, 1.9, 1.5, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Green Lentils', 'Groene linzen', 'Generic', 'supermarket', 'albert_heijn', NULL, 'granen', 100, '100g gekookt', 105, 8.9, 18.0, 0.3, 3.0, 0.4, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Brown Lentils', 'Bruine linzen', 'Generic', 'supermarket', 'albert_heijn', NULL, 'granen', 100, '100g gekookt', 103, 8.8, 17.5, 0.3, 2.7, 0.3, true);

-- MEAL PREP STAPLES - BONEN (Beans)
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Chickpeas Dried', 'Kikkererwten (gedroogd)', 'Generic', 'supermarket', 'albert_heijn', NULL, 'granen', 100, '100g gekookt', 134, 8.9, 22.5, 2.1, 3.0, 4.0, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Chickpeas Canned', 'Kikkererwten (blik)', 'Generic', 'supermarket', 'albert_heijn', NULL, 'granen', 100, '100g (uitlekgewicht)', 119, 7.2, 19.5, 1.6, 2.4, 2.8, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Kidney Beans Canned', 'Kidney bonen (blik)', 'Generic', 'supermarket', 'albert_heijn', NULL, 'granen', 100, '100g (uitlekgewicht)', 127, 8.5, 21.0, 0.3, 2.1, 0.2, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Black Beans Canned', 'Zwarte bonen (blik)', 'Generic', 'supermarket', 'albert_heijn', NULL, 'granen', 100, '100g (uitlekgewicht)', 132, 8.9, 23.7, 0.5, 2.0, 0.0, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('White Beans Canned', 'Witte bonen (blik)', 'Generic', 'supermarket', 'albert_heijn', NULL, 'granen', 100, '100g (uitlekgewicht)', 102, 7.3, 17.7, 0.3, 1.6, 0.0, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Cannellini Beans', 'Cannellini bonen', 'Generic', 'supermarket', 'albert_heijn', NULL, 'granen', 100, '100g gekookt', 105, 8.0, 17.0, 0.4, 1.5, 0.0, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Edamame Beans', 'Edamame bonen', 'Generic', 'supermarket', 'albert_heijn', NULL, 'granen', 100, '100g gekookt', 111, 11.3, 8.0, 5.2, 2.2, 2.0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Soybeans', 'Sojabonen', 'Generic', 'supermarket', 'albert_heijn', NULL, 'granen', 100, '100g gekookt', 173, 16.6, 11.0, 9.0, 4.0, 3.0, false);

-- BAKKERIJ - BROOD (Bread)
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Croissant', 'Croissant', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'brood', 60, '1 croissant', 395, 8.0, 39.0, 20.0, 1.5, 8.0, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Pain au Chocolat', 'Pain au chocolat', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'brood', 70, '1 stuks', 410, 7.5, 41.0, 21.5, 1.2, 14.0, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Cream Roll', 'Roombroodje', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'brood', 65, '1 stuks', 380, 7.0, 42.0, 18.0, 1.0, 18.0, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Sausage Roll', 'Saucijzenbroodje', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'brood', 75, '1 stuks', 380, 11.0, 35.0, 19.0, 1.2, 2.0, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Apple Danish', 'Appelflap', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'brood', 70, '1 stuks', 330, 6.0, 42.0, 14.0, 1.5, 20.0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Tompoes', 'Tompoes', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'brood', 85, '1 stuks', 385, 6.0, 43.0, 20.0, 0.5, 25.0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Currant Bun', 'Krentenbol', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'brood', 60, '1 stuks', 310, 7.5, 52.0, 5.0, 2.0, 22.0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Raisin Bread', 'Rozijnenbrood', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'brood', 50, '1 snee', 310, 7.0, 50.0, 5.5, 2.5, 18.0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Sugar Bread Frisian', 'Suikerbrood (Fries)', 'Generic', 'supermarket', 'albert_heijn', NULL, 'brood', 55, '1 stuks', 330, 7.0, 52.0, 6.0, 2.0, 20.0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Gingerbread', 'Ontbijtkoek (Peijnenburg)', 'Peijnenburg', 'supermarket', 'albert_heijn', NULL, 'brood', 40, '1 stuks', 329, 5.0, 62.0, 3.5, 1.0, 24.0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Sausage Bread Brabant', 'Worstenbroodje (Brabants)', 'Generic', 'supermarket', 'albert_heijn', NULL, 'brood', 80, '1 stuks', 370, 12.0, 35.0, 17.0, 1.0, 2.0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Pie Limburgian', 'Vlaai (Limburgs, 1 punt)', 'Generic', 'supermarket', 'albert_heijn', NULL, 'brood', 90, '1 punt', 285, 5.0, 38.0, 11.0, 1.5, 18.0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Oil Donut', 'Oliebollen (1 stuk)', 'Generic', 'supermarket', 'albert_heijn', NULL, 'brood', 50, '1 stuk', 380, 4.0, 45.0, 18.0, 1.0, 20.0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Den Bosch Bun', 'Bossche Bol (1 stuk)', 'Generic', 'supermarket', 'albert_heijn', NULL, 'brood', 120, '1 stuk', 320, 6.0, 38.0, 14.0, 1.0, 24.0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Plain Bagel', 'Bagel plain', 'Generic', 'supermarket', 'albert_heijn', NULL, 'brood', 85, '1 stuks', 248, 9.2, 48.0, 1.6, 2.5, 5.0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Sesame Bagel', 'Bagel sesam', 'Generic', 'supermarket', 'albert_heijn', NULL, 'brood', 85, '1 stuks', 270, 9.5, 47.0, 3.5, 2.5, 5.0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Ciabatta', 'Ciabatta', 'Generic', 'supermarket', 'albert_heijn', NULL, 'brood', 50, '1 snee', 282, 8.0, 50.0, 2.0, 2.2, 1.0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Focaccia', 'Focaccia', 'Generic', 'supermarket', 'albert_heijn', NULL, 'brood', 60, '1 stuks', 310, 8.0, 48.0, 7.0, 1.5, 2.0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Rye Bread', 'Roggebrood', 'Generic', 'supermarket', 'albert_heijn', NULL, 'brood', 50, '1 snee', 259, 8.5, 48.0, 1.0, 4.0, 1.0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Pumpernickel', 'Pumpernickel', 'Generic', 'supermarket', 'albert_heijn', NULL, 'brood', 50, '1 snee', 258, 7.0, 48.6, 0.5, 3.5, 1.0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Crispbread', 'Knäckebröd (Wasa)', 'Wasa', 'supermarket', 'albert_heijn', NULL, 'brood', 10, '1 stuks', 321, 10.0, 60.0, 3.0, 7.0, 1.0, false);

-- BROODBELEG - PASTA & SPREADS
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Peanut Butter Calvé', 'Pindakaas Calvé', 'Calvé', 'supermarket', 'albert_heijn', NULL, 'broodbeleg', 15, '1 eetlepel', 588, 25.0, 20.0, 50.0, 3.6, 7.0, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Peanut Butter AH', 'Pindakaas AH', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'broodbeleg', 15, '1 eetlepel', 586, 25.5, 18.0, 49.0, 3.5, 6.5, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Nutella', 'Nutella', 'Nutella', 'supermarket', 'albert_heijn', NULL, 'broodbeleg', 15, '1 eetlepel', 542, 7.0, 57.0, 30.5, 1.3, 56.0, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Chocolate Spread AH', 'Chocopasta AH', 'Albert Heijn', 'supermarket', 'albert_heijn', NULL, 'broodbeleg', 15, '1 eetlepel', 530, 6.0, 58.0, 28.0, 1.5, 54.0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Hagelslag Milk', 'Hagelslag melk (De Ruijter)', 'De Ruijter', 'supermarket', 'albert_heijn', NULL, 'broodbeleg', 5, '1 tl', 463, 2.0, 98.0, 0.5, 0.0, 85.0, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Hagelslag Dark', 'Hagelslag puur (De Ruijter)', 'De Ruijter', 'supermarket', 'albert_heijn', NULL, 'broodbeleg', 5, '1 tl', 455, 3.0, 98.0, 0.5, 0.5, 83.0, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Sprinkles Milk', 'Vlokken melk', 'De Ruijter', 'supermarket', 'albert_heijn', NULL, 'broodbeleg', 5, '1 tl', 465, 1.5, 98.0, 1.0, 0.0, 86.0, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Sprinkles Dark', 'Vlokken puur', 'De Ruijter', 'supermarket', 'albert_heijn', NULL, 'broodbeleg', 5, '1 tl', 460, 2.5, 98.0, 0.5, 0.5, 84.0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Apple Syrup', 'Appelstroop', 'Generic', 'supermarket', 'albert_heijn', NULL, 'broodbeleg', 15, '1 eetlepel', 258, 0.2, 65.0, 0.1, 0.0, 46.0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Apple Syrup Rinse', 'Rinse appelstroop', 'Rinse', 'supermarket', 'albert_heijn', NULL, 'broodbeleg', 15, '1 eetlepel', 260, 0.3, 65.0, 0.0, 0.0, 47.0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Liquid Honey', 'Honing (vloeibaar)', 'Generic', 'supermarket', 'albert_heijn', NULL, 'broodbeleg', 15, '1 eetlepel', 304, 0.3, 82.0, 0.0, 0.0, 82.0, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Jam Strawberry', 'Jam aardbei (Hero)', 'Hero', 'supermarket', 'albert_heijn', NULL, 'broodbeleg', 15, '1 eetlepel', 278, 0.3, 70.0, 0.1, 0.0, 56.0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Jam Apricot', 'Jam abrikoos (Hero)', 'Hero', 'supermarket', 'albert_heijn', NULL, 'broodbeleg', 15, '1 eetlepel', 275, 0.2, 70.0, 0.0, 0.0, 55.0, false);

-- BROODBELEG - VLEESWAREN (Meat Products)
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Filet Americain', 'Filet Americain', 'Generic', 'supermarket', 'albert_heijn', NULL, 'broodbeleg', 50, '2 plakken', 315, 15.0, 1.0, 26.0, 0.0, 0.5, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Liver Wurst', 'Leverworst', 'Generic', 'supermarket', 'albert_heijn', NULL, 'broodbeleg', 50, '2 plakken', 283, 16.0, 2.0, 22.0, 0.0, 0.5, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Chicken Fillet Lunch', 'Kipfilet vleeswaren', 'Generic', 'supermarket', 'albert_heijn', NULL, 'broodbeleg', 50, '2 plakken', 148, 24.0, 1.0, 5.5, 0.0, 0.5, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Smoked Beef', 'Runderrookvlees', 'Generic', 'supermarket', 'albert_heijn', NULL, 'broodbeleg', 50, '2 plakken', 134, 26.0, 1.0, 2.5, 0.0, 0.0, true);

-- BROODBELEG - SALADE (Spreads)
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Tuna Salad', 'Tonijnsalade', 'Generic', 'supermarket', 'albert_heijn', NULL, 'broodbeleg', 50, '2 eetlepels', 218, 16.0, 3.0, 15.0, 0.0, 1.0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Egg Salad', 'Eiersalade', 'Generic', 'supermarket', 'albert_heijn', NULL, 'broodbeleg', 50, '2 eetlepels', 285, 10.0, 3.0, 25.0, 0.0, 0.5, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Shrimp Salad', 'Krabsalade', 'Generic', 'supermarket', 'albert_heijn', NULL, 'broodbeleg', 50, '2 eetlepels', 195, 12.0, 4.0, 14.0, 0.0, 1.0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Dutch Salad', 'Huzarensalade', 'Generic', 'supermarket', 'albert_heijn', NULL, 'broodbeleg', 50, '2 eetlepels', 210, 8.0, 5.0, 17.0, 0.5, 2.0, false);

-- SUPERMARKET BRANDS - JUMBO
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Chicken Fillet Jumbo', 'Jumbo Kipfilet', 'Jumbo', 'supermarket', 'jumbo', NULL, 'vlees', 150, '150g', 165, 31.0, 0.0, 3.6, 0.0, 0.0, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Whole Grain Bread Jumbo', 'Jumbo Volkoren brood', 'Jumbo', 'supermarket', 'jumbo', NULL, 'brood', 50, '1 snee', 260, 8.5, 48.0, 1.2, 4.0, 1.0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Semi-Skimmed Milk Jumbo', 'Jumbo Halfvolle melk', 'Jumbo', 'supermarket', 'jumbo', NULL, 'zuivel', 200, '200ml', 49, 3.4, 4.8, 1.6, 0.0, 4.8, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Lean Quark Jumbo', 'Jumbo Magere kwark', 'Jumbo', 'supermarket', 'jumbo', NULL, 'zuivel', 150, '150g', 68, 12.0, 4.0, 0.5, 0.0, 3.5, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Peanut Butter Jumbo', 'Jumbo Pindakaas', 'Jumbo', 'supermarket', 'jumbo', NULL, 'broodbeleg', 15, '1 eetlepel', 585, 25.0, 19.0, 49.5, 3.4, 6.5, true);

-- SUPERMARKET BRANDS - LIDL
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Yogurt Milbona', 'Lidl Milbona Yoghurt', 'Milbona', 'supermarket', 'lidl', NULL, 'zuivel', 150, '150g', 63, 3.5, 4.5, 3.0, 0.0, 4.0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Quark Milbona', 'Lidl Milbona Kwark', 'Milbona', 'supermarket', 'lidl', NULL, 'zuivel', 150, '150g', 70, 11.5, 4.2, 0.8, 0.0, 3.8, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Chicken Fillet Pikok', 'Lidl Pikok Kipfilet', 'Pikok', 'supermarket', 'lidl', NULL, 'vlees', 150, '150g', 165, 30.5, 0.0, 3.8, 0.0, 0.0, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Salmon Rivercote', 'Lidl Rivercote Zalm', 'Rivercote', 'supermarket', 'lidl', NULL, 'vis', 150, '150g', 208, 20.0, 0.0, 13.6, 0.0, 0.0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Whole Grain Bread Belbake', 'Lidl Belbake Volkoren brood', 'Belbake', 'supermarket', 'lidl', NULL, 'brood', 50, '1 snee', 261, 8.6, 48.5, 1.1, 4.2, 0.9, false);

-- SUPERMARKET BRANDS - ALDI
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Lean Quark Aldi', 'Aldi Magere kwark', 'Aldi', 'supermarket', 'aldi', NULL, 'zuivel', 150, '150g', 68, 12.0, 4.0, 0.5, 0.0, 3.5, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Chicken Fillet Aldi', 'Aldi Kipfilet naturel', 'Aldi', 'supermarket', 'aldi', NULL, 'vlees', 150, '150g', 165, 31.0, 0.0, 3.6, 0.0, 0.0, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Whole Grain Bread Aldi', 'Aldi Volkoren brood', 'Aldi', 'supermarket', 'aldi', NULL, 'brood', 50, '1 snee', 261, 8.5, 48.0, 1.2, 4.1, 0.9, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Semi-Skimmed Milk Aldi', 'Aldi Halfvolle melk', 'Aldi', 'supermarket', 'aldi', NULL, 'zuivel', 200, '200ml', 49, 3.4, 4.8, 1.6, 0.0, 4.8, false);

-- SAUCES & CONDIMENTS
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Ketchup', 'Ketchup (Heinz)', 'Heinz', 'supermarket', 'albert_heijn', NULL, 'saus', 15, '1 eetlepel', 136, 1.3, 29.0, 0.2, 0.4, 24.0, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Mayonnaise', 'Mayonaise (Calvé)', 'Calvé', 'supermarket', 'albert_heijn', NULL, 'saus', 10, '1 eetlepel', 717, 0.3, 0.6, 80.0, 0.0, 0.0, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Fries Sauce', 'Fritessaus (Remia)', 'Remia', 'supermarket', 'albert_heijn', NULL, 'saus', 15, '1 eetlepel', 700, 0.5, 1.0, 78.0, 0.0, 0.5, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Curry Ketchup', 'Curry ketchup (Hela)', 'Hela', 'supermarket', 'albert_heijn', NULL, 'saus', 15, '1 eetlepel', 142, 1.0, 30.0, 0.2, 0.3, 24.0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Mustard', 'Mosterd (Zaanse)', 'Zaanse', 'supermarket', 'albert_heijn', NULL, 'saus', 5, '1 tl', 66, 3.6, 3.3, 4.0, 0.4, 0.6, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Sambal', 'Sambal (Conimex)', 'Conimex', 'supermarket', 'albert_heijn', NULL, 'saus', 5, '1 tl', 89, 1.5, 10.0, 4.5, 1.0, 4.0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Sriracha', 'Sriracha (Flying Goose)', 'Flying Goose', 'supermarket', 'albert_heijn', NULL, 'saus', 5, '1 tl', 125, 2.0, 23.0, 3.5, 1.5, 8.0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Soy Sauce', 'Sojasaus (Kikkoman)', 'Kikkoman', 'supermarket', 'albert_heijn', NULL, 'saus', 5, '1 tl', 68, 11.0, 4.9, 0.5, 0.0, 1.0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Green Pesto', 'Pesto groen (Grand''Italia)', 'Grand''Italia', 'supermarket', 'albert_heijn', NULL, 'saus', 10, '1 eetlepel', 580, 7.0, 6.0, 60.0, 1.5, 1.0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Red Pesto', 'Pesto rood (Grand''Italia)', 'Grand''Italia', 'supermarket', 'albert_heijn', NULL, 'saus', 10, '1 eetlepel', 560, 5.0, 8.0, 58.0, 1.2, 4.0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('BBQ Sauce', 'BBQ saus (Heinz)', 'Heinz', 'supermarket', 'albert_heijn', NULL, 'saus', 15, '1 eetlepel', 142, 1.0, 32.0, 0.2, 0.2, 28.0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Cocktail Sauce', 'Cocktailsaus', 'Generic', 'supermarket', 'albert_heijn', NULL, 'saus', 15, '1 eetlepel', 120, 0.5, 28.0, 0.3, 0.0, 22.0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Garlic Sauce', 'Knoflooksaus', 'Generic', 'supermarket', 'albert_heijn', NULL, 'saus', 15, '1 eetlepel', 560, 1.0, 2.0, 60.0, 0.0, 0.5, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Andalouse Sauce', 'Andalouse saus', 'Generic', 'supermarket', 'albert_heijn', NULL, 'saus', 15, '1 eetlepel', 540, 0.5, 3.0, 58.0, 0.0, 1.0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Tabasco', 'Tabasco', 'Tabasco', 'supermarket', 'albert_heijn', NULL, 'saus', 2, 'few drops', 61, 0.2, 0.0, 0.0, 0.0, 0.0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Sweet Chili Sauce', 'Sweet chili saus (Blue Dragon)', 'Blue Dragon', 'supermarket', 'albert_heijn', NULL, 'saus', 15, '1 eetlepel', 140, 0.5, 33.0, 0.0, 0.0, 31.0, false);
