-- Fast Food and Restaurant Chain Products Seed Data
-- Dutch/Belgian market nutritional values per 100g

-- McDonald's Products (~20 items)
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Big Mac', 'Big Mac', 'McDonald''s', 'restaurant', 'manual', NULL, 'fast_food', 215, '1 burger', 257, 12.0, 31.0, 11.0, 1.5, 7.0, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Quarter Pounder', 'Quarter Pounder', 'McDonald''s', 'restaurant', 'manual', NULL, 'fast_food', 196, '1 burger', 280, 14.0, 27.0, 14.0, 1.2, 5.0, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('McChicken', 'McChicken', 'McDonald''s', 'restaurant', 'manual', NULL, 'fast_food', 150, '1 burger', 280, 12.0, 30.0, 13.0, 1.0, 3.0, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Cheeseburger', 'Cheeseburger', 'McDonald''s', 'restaurant', 'manual', NULL, 'fast_food', 117, '1 burger', 265, 12.0, 30.0, 11.0, 1.5, 4.0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Hamburger', 'Hamburger', 'McDonald''s', 'restaurant', 'manual', NULL, 'fast_food', 105, '1 burger', 245, 11.0, 29.0, 9.0, 1.5, 3.0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('McNuggets 6 pieces', 'McNuggets 6 stuks', 'McDonald''s', 'restaurant', 'manual', NULL, 'fast_food', 140, '6 stuks', 305, 18.0, 19.0, 17.0, 0.8, 0.0, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('McNuggets 9 pieces', 'McNuggets 9 stuks', 'McDonald''s', 'restaurant', 'manual', NULL, 'fast_food', 210, '9 stuks', 305, 18.0, 19.0, 17.0, 0.8, 0.0, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Filet-O-Fish', 'Filet-O-Fish', 'McDonald''s', 'restaurant', 'manual', NULL, 'fast_food', 155, '1 burger', 250, 11.0, 31.0, 10.0, 1.0, 3.0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('McFlurry M&M', 'McFlurry M&M', 'McDonald''s', 'restaurant', 'manual', NULL, 'fast_food', 290, '1 cup', 195, 5.0, 30.0, 7.0, 0.0, 25.0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('McFlurry Oreo', 'McFlurry Oreo', 'McDonald''s', 'restaurant', 'manual', NULL, 'fast_food', 290, '1 cup', 195, 5.0, 31.0, 7.0, 0.0, 26.0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Frietjes klein', 'Frietjes klein', 'McDonald''s', 'restaurant', 'manual', NULL, 'fast_food', 75, 'klein', 325, 3.5, 41.0, 15.0, 3.5, 0.2, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Frietjes medium', 'Frietjes medium', 'McDonald''s', 'restaurant', 'manual', NULL, 'fast_food', 117, 'medium', 325, 3.5, 41.0, 15.0, 3.5, 0.2, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Frietjes groot', 'Frietjes groot', 'McDonald''s', 'restaurant', 'manual', NULL, 'fast_food', 154, 'groot', 325, 3.5, 41.0, 15.0, 3.5, 0.2, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Big Tasty', 'Big Tasty', 'McDonald''s', 'restaurant', 'manual', NULL, 'fast_food', 230, '1 burger', 265, 12.0, 31.0, 11.0, 1.2, 6.0, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Chicken Wrap', 'Chicken Wrap', 'McDonald''s', 'restaurant', 'manual', NULL, 'fast_food', 227, '1 wrap', 235, 14.0, 27.0, 8.0, 2.0, 2.0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Caesar Salad', 'Caesar Salad', 'McDonald''s', 'restaurant', 'manual', NULL, 'fast_food', 165, '1 salade', 135, 9.0, 8.0, 8.0, 3.0, 2.0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Apple Pie', 'Apple Pie', 'McDonald''s', 'restaurant', 'manual', NULL, 'fast_food', 83, '1 pie', 284, 3.0, 38.0, 13.0, 1.5, 20.0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('McDouble', 'McDouble', 'McDonald''s', 'restaurant', 'manual', NULL, 'fast_food', 162, '1 burger', 275, 14.0, 28.0, 12.0, 1.5, 4.0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('McMuffin Egg Bacon', 'McMuffin Ei Bacon', 'McDonald''s', 'restaurant', 'manual', NULL, 'fast_food', 135, '1 muffin', 285, 15.0, 28.0, 12.0, 1.2, 3.0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Pancakes', 'Pannenkoeken', 'McDonald''s', 'restaurant', 'manual', NULL, 'fast_food', 110, '3 stuks', 258, 5.0, 35.0, 10.0, 1.0, 15.0, false);

-- Burger King Products (~10 items)
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Whopper', 'Whopper', 'Burger King', 'restaurant', 'manual', NULL, 'fast_food', 215, '1 burger', 272, 12.0, 29.0, 13.0, 1.5, 5.0, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Whopper Jr', 'Whopper Jr', 'Burger King', 'restaurant', 'manual', NULL, 'fast_food', 140, '1 burger', 275, 11.0, 30.0, 13.0, 1.4, 5.0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Long Chicken', 'Long Chicken', 'Burger King', 'restaurant', 'manual', NULL, 'fast_food', 165, '1 burger', 260, 14.0, 28.0, 11.0, 1.0, 2.0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Chicken Nuggets King', 'Chicken Nuggets King', 'Burger King', 'restaurant', 'manual', NULL, 'fast_food', 180, '10 stuks', 310, 17.0, 20.0, 17.0, 0.8, 0.0, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Crispy Chicken', 'Crispy Chicken', 'Burger King', 'restaurant', 'manual', NULL, 'fast_food', 145, '1 burger', 275, 13.0, 30.0, 12.0, 1.0, 3.0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('King Fries medium', 'King Friet medium', 'Burger King', 'restaurant', 'manual', NULL, 'fast_food', 111, 'medium', 320, 3.2, 41.0, 14.5, 3.5, 0.1, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Onion Rings', 'Ui Ringen', 'Burger King', 'restaurant', 'manual', NULL, 'fast_food', 100, '1 portie', 290, 3.0, 35.0, 14.0, 3.0, 1.0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Chili Cheese Bites', 'Chili Cheese Bites', 'Burger King', 'restaurant', 'manual', NULL, 'fast_food', 80, '1 portie', 275, 10.0, 28.0, 13.0, 2.0, 3.0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Double Whopper', 'Double Whopper', 'Burger King', 'restaurant', 'manual', NULL, 'fast_food', 290, '1 burger', 310, 18.0, 28.0, 16.0, 1.5, 5.0, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Plant-Based Whopper', 'Plant-Based Whopper', 'Burger King', 'restaurant', 'manual', NULL, 'fast_food', 215, '1 burger', 260, 10.0, 30.0, 12.0, 4.0, 4.0, false);

-- KFC Products (~8 items)
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Original Bucket 1 piece', 'Original Bucket 1 stuk', 'KFC', 'restaurant', 'manual', NULL, 'fast_food', 85, '1 stuk', 280, 20.0, 15.0, 15.0, 0.5, 0.0, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Hot Wings 6 pieces', 'Hot Wings 6 stuks', 'KFC', 'restaurant', 'manual', NULL, 'fast_food', 120, '6 stuks', 290, 22.0, 12.0, 16.0, 0.3, 0.0, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Zinger Burger', 'Zinger Burger', 'KFC', 'restaurant', 'manual', NULL, 'fast_food', 155, '1 burger', 265, 14.0, 26.0, 11.0, 1.0, 2.0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Kentucky Burger', 'Kentucky Burger', 'KFC', 'restaurant', 'manual', NULL, 'fast_food', 145, '1 burger', 260, 13.0, 27.0, 10.0, 1.0, 2.0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Coleslaw', 'Coleslaw', 'KFC', 'restaurant', 'manual', NULL, 'fast_food', 110, '1 portie', 125, 1.5, 15.0, 5.0, 2.0, 10.0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Corn on the Cob', 'Maïs op de Kolf', 'KFC', 'restaurant', 'manual', NULL, 'fast_food', 90, '1 stuk', 96, 3.5, 18.0, 1.5, 2.5, 3.0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Popcorn Chicken', 'Popcorn Chicken', 'KFC', 'restaurant', 'manual', NULL, 'fast_food', 100, '1 portion', 310, 19.0, 18.0, 17.0, 0.5, 0.0, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Fillet Burger', 'Filet Burger', 'KFC', 'restaurant', 'manual', NULL, 'fast_food', 140, '1 burger', 255, 12.0, 28.0, 9.0, 1.0, 2.0, false);

-- Domino's Pizza Products (~10 items)
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Margherita medium 1 slice', 'Margherita medium 1 plak', 'Domino''s Pizza', 'restaurant', 'manual', NULL, 'fast_food', 72, '1 plak', 245, 8.5, 30.0, 10.0, 1.5, 2.0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Pepperoni medium 1 slice', 'Pepperoni medium 1 plak', 'Domino''s Pizza', 'restaurant', 'manual', NULL, 'fast_food', 78, '1 plak', 270, 10.0, 29.0, 12.0, 1.5, 2.0, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('BBQ Chicken medium 1 slice', 'BBQ Chicken medium 1 plak', 'Domino''s Pizza', 'restaurant', 'manual', NULL, 'fast_food', 75, '1 plak', 255, 11.0, 30.0, 10.0, 1.5, 3.0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Hawaii medium 1 slice', 'Hawaii medium 1 plak', 'Domino''s Pizza', 'restaurant', 'manual', NULL, 'fast_food', 76, '1 plak', 260, 9.0, 32.0, 10.0, 1.5, 5.0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Mighty Meaty 1 slice', 'Mighty Meaty 1 plak', 'Domino''s Pizza', 'restaurant', 'manual', NULL, 'fast_food', 82, '1 plak', 295, 13.0, 28.0, 13.0, 1.5, 2.0, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Garlic Bread', 'Knoflookbrood', 'Domino''s Pizza', 'restaurant', 'manual', NULL, 'fast_food', 60, '1 stuk', 345, 7.0, 32.0, 20.0, 2.0, 2.0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Chicken Kickers', 'Chicken Kickers', 'Domino''s Pizza', 'restaurant', 'manual', NULL, 'fast_food', 100, '5 stuks', 280, 17.0, 20.0, 14.0, 0.5, 1.0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Buffalo Wings', 'Buffalo Wings', 'Domino''s Pizza', 'restaurant', 'manual', NULL, 'fast_food', 90, '6 stuks', 300, 19.0, 15.0, 17.0, 0.3, 1.0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Veggie medium 1 slice', 'Veggie medium 1 plak', 'Domino''s Pizza', 'restaurant', 'manual', NULL, 'fast_food', 68, '1 plak', 235, 7.5, 31.0, 8.5, 2.0, 2.0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Tuna medium 1 slice', 'Tonijn medium 1 plak', 'Domino''s Pizza', 'restaurant', 'manual', NULL, 'fast_food', 76, '1 plak', 250, 10.0, 29.0, 10.0, 1.5, 2.0, false);

-- New York Pizza Products (~5 items)
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Margherita 1 slice', 'Margherita 1 plak', 'New York Pizza', 'restaurant', 'manual', NULL, 'fast_food', 75, '1 plak', 248, 8.5, 31.0, 10.0, 1.5, 2.0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Pepperoni 1 slice', 'Pepperoni 1 plak', 'New York Pizza', 'restaurant', 'manual', NULL, 'fast_food', 80, '1 plak', 272, 10.5, 30.0, 12.0, 1.5, 2.0, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Shoarma 1 slice', 'Shoarma 1 plak', 'New York Pizza', 'restaurant', 'manual', NULL, 'fast_food', 82, '1 plak', 280, 12.0, 30.0, 12.0, 1.5, 2.0, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('BBQ Chicken 1 slice', 'BBQ Chicken 1 plak', 'New York Pizza', 'restaurant', 'manual', NULL, 'fast_food', 76, '1 plak', 258, 11.0, 31.0, 10.0, 1.5, 3.0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Garlic Bread', 'Knoflookbrood', 'New York Pizza', 'restaurant', 'manual', NULL, 'fast_food', 60, '1 stuk', 348, 7.0, 32.0, 20.5, 2.0, 2.0, false);

-- Subway Products (~8 items)
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Italian BMT 15cm', 'Italian BMT 15cm', 'Subway', 'restaurant', 'manual', NULL, 'fast_food', 160, '1 sub', 240, 12.0, 32.0, 8.0, 2.0, 3.0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Chicken Teriyaki 15cm', 'Chicken Teriyaki 15cm', 'Subway', 'restaurant', 'manual', NULL, 'fast_food', 155, '1 sub', 235, 14.0, 34.0, 5.5, 2.0, 6.0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Tuna 15cm', 'Tonijn 15cm', 'Subway', 'restaurant', 'manual', NULL, 'fast_food', 155, '1 sub', 245, 11.0, 31.0, 9.0, 2.0, 3.0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Veggie Delite 15cm', 'Veggie Delite 15cm', 'Subway', 'restaurant', 'manual', NULL, 'fast_food', 145, '1 sub', 190, 7.0, 35.0, 3.0, 3.5, 4.0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Meatball Marinara 15cm', 'Meatball Marinara 15cm', 'Subway', 'restaurant', 'manual', NULL, 'fast_food', 155, '1 sub', 250, 12.0, 32.0, 9.0, 2.0, 5.0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Turkey Breast 15cm', 'Turkey Breast 15cm', 'Subway', 'restaurant', 'manual', NULL, 'fast_food', 150, '1 sub', 215, 13.0, 33.0, 4.0, 2.0, 3.0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Chicken Fajita 15cm', 'Chicken Fajita 15cm', 'Subway', 'restaurant', 'manual', NULL, 'fast_food', 150, '1 sub', 220, 14.0, 31.0, 5.0, 2.0, 4.0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Steak & Cheese 15cm', 'Steak & Cheese 15cm', 'Subway', 'restaurant', 'manual', NULL, 'fast_food', 155, '1 sub', 245, 15.0, 31.0, 8.0, 2.0, 3.0, false);

-- FEBO Products (~5 items)
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Kroket', 'Kroket', 'FEBO', 'restaurant', 'manual', NULL, 'fast_food', 85, '1 stuk', 285, 8.0, 22.0, 18.0, 1.0, 1.0, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Frikandel', 'Frikandel', 'FEBO', 'restaurant', 'manual', NULL, 'fast_food', 100, '1 stuk', 300, 10.0, 2.0, 28.0, 0.0, 0.0, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Kaassouflé', 'Kaassouflé', 'FEBO', 'restaurant', 'manual', NULL, 'fast_food', 80, '1 stuk', 310, 9.0, 20.0, 22.0, 1.0, 2.0, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Berenhap', 'Berenhap', 'FEBO', 'restaurant', 'manual', NULL, 'fast_food', 75, '1 stuk', 290, 7.0, 25.0, 18.0, 0.8, 1.0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Bamischijf', 'Bamischijf', 'FEBO', 'restaurant', 'manual', NULL, 'fast_food', 90, '1 stuk', 305, 6.0, 28.0, 18.0, 2.0, 2.0, true);

-- Dutch Snackbar Products (~10 items)
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Friet with mayo', 'Friet met mayo', 'Dutch Snackbar', 'restaurant', 'manual', NULL, 'fast_food', 170, '1 portie', 310, 3.5, 36.0, 16.0, 3.5, 0.2, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Friet with special sauce', 'Friet met oorlog', 'Dutch Snackbar', 'restaurant', 'manual', NULL, 'fast_food', 175, '1 portie', 330, 3.5, 35.0, 18.0, 3.5, 1.0, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Kapsalon', 'Kapsalon', 'Dutch Snackbar', 'restaurant', 'manual', NULL, 'fast_food', 250, '1 portie', 245, 14.0, 28.0, 9.0, 3.0, 3.0, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Shoarma platter', 'Shoarma schotel', 'Dutch Snackbar', 'restaurant', 'manual', NULL, 'fast_food', 280, '1 schotel', 260, 16.0, 30.0, 10.0, 2.5, 3.0, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Shoarma sandwich', 'Broodje shoarma', 'Dutch Snackbar', 'restaurant', 'manual', NULL, 'fast_food', 150, '1 broodje', 250, 14.0, 28.0, 9.0, 2.0, 2.0, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Frikandel sandwich special', 'Broodje frikandel speciaal', 'Dutch Snackbar', 'restaurant', 'manual', NULL, 'fast_food', 140, '1 broodje', 275, 10.0, 24.0, 14.0, 1.5, 2.0, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Spring roll', 'Loempia', 'Dutch Snackbar', 'restaurant', 'manual', NULL, 'fast_food', 50, '1 stuk', 295, 6.0, 25.0, 17.0, 1.0, 1.0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Bami goreng', 'Bami goreng', 'Dutch Snackbar', 'restaurant', 'manual', NULL, 'fast_food', 210, '1 portie', 155, 6.0, 18.0, 6.0, 2.0, 2.0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Nasi goreng', 'Nasi goreng', 'Dutch Snackbar', 'restaurant', 'manual', NULL, 'fast_food', 210, '1 portie', 160, 5.5, 19.0, 6.5, 2.0, 2.0, false);
