-- Extra food products to reach 750+ total (adding ~270 products)
-- Current count: 484, Target: 750+

-- BEREIDE MAALTIJDEN / KANT-EN-KLAAR (40 products)
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('AH Verse Caesar Salade', 'AH Verse Caesar Salade', 'Albert Heijn', 'Supermarket', 'albert_heijn', NULL, 'snack', 200, '200g', 150, 8, 8, 10, 2, 2, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('AH Tonijnsalade', 'AH Tonijnsalade', 'Albert Heijn', 'Supermarket', 'albert_heijn', NULL, 'snack', 200, '200g', 165, 16, 5, 8, 2, 1, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('AH Pastasalade', 'AH Pastasalade', 'Albert Heijn', 'Supermarket', 'albert_heijn', NULL, 'snack', 200, '200g', 145, 5, 18, 6, 2, 3, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('AH Tomatenseoup', 'AH Tomatenseoup', 'Albert Heijn', 'Supermarket', 'albert_heijn', NULL, 'snack', 200, '200ml', 35, 2, 6, 1, 1, 3, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('AH Kippensoep', 'AH Kippensoep', 'Albert Heijn', 'Supermarket', 'albert_heijn', NULL, 'snack', 200, '200ml', 45, 5, 4, 1, 1, 1, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('AH Erwtensoep', 'AH Erwtensoep', 'Albert Heijn', 'Supermarket', 'albert_heijn', NULL, 'snack', 200, '200ml', 70, 6, 10, 1, 3, 2, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('AH Minestrone', 'AH Minestrone', 'Albert Heijn', 'Supermarket', 'albert_heijn', NULL, 'snack', 200, '200ml', 45, 3, 7, 1, 2, 2, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Cup-a-Soup Tomaat', 'Cup-a-Soup Tomaat', 'Unilever', 'Supermarket', 'albert_heijn', NULL, 'snack', 180, '180ml', 40, 1, 8, 0.5, 0, 2, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Cup-a-Soup Paddenstoel', 'Cup-a-Soup Paddenstoel', 'Unilever', 'Supermarket', 'albert_heijn', NULL, 'snack', 180, '180ml', 42, 1, 8, 0.7, 0, 1, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Cup-a-Soup Kip', 'Cup-a-Soup Kip', 'Unilever', 'Supermarket', 'albert_heijn', NULL, 'snack', 180, '180ml', 38, 2, 7, 0.5, 0, 1, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Unox Kippensoep blik', 'Unox Kippensoep blik', 'Unilever', 'Supermarket', 'albert_heijn', NULL, 'snack', 200, '200ml', 48, 5, 4, 2, 1, 1, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Unox Erwtensoep blik', 'Unox Erwtensoep blik', 'Unilever', 'Supermarket', 'albert_heijn', NULL, 'snack', 200, '200ml', 72, 6, 11, 2, 3, 2, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Unox Witloofsoep blik', 'Unox Witloofsoep blik', 'Unilever', 'Supermarket', 'albert_heijn', NULL, 'snack', 200, '200ml', 45, 3, 5, 2, 2, 1, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Dr. Oetker Ristorante Pizza Margherita', 'Dr. Oetker Ristorante Pizza Margherita', 'Dr. Oetker', 'Supermarket', 'albert_heijn', NULL, 'snack', 300, '300g', 260, 10, 32, 10, 2, 2, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Dr. Oetker Ristorante Pizza Salami', 'Dr. Oetker Ristorante Pizza Salami', 'Dr. Oetker', 'Supermarket', 'albert_heijn', NULL, 'snack', 300, '300g', 280, 12, 32, 12, 2, 1, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Wagner Pizza Steinofen', 'Wagner Pizza Steinofen', 'Wagner', 'Supermarket', 'albert_heijn', NULL, 'snack', 330, '330g', 275, 11, 34, 11, 2, 2, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('AH Diepvries Pizza', 'AH Diepvries Pizza', 'Albert Heijn', 'Supermarket', 'albert_heijn', NULL, 'snack', 300, '300g', 250, 9, 30, 9, 2, 1, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('AH Lasagne Bolognese', 'AH Lasagne Bolognese', 'Albert Heijn', 'Supermarket', 'albert_heijn', NULL, 'snack', 400, '400g', 145, 10, 14, 5, 1, 2, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('AH Lasagne Groente', 'AH Lasagne Groente', 'Albert Heijn', 'Supermarket', 'albert_heijn', NULL, 'snack', 400, '400g', 120, 7, 15, 3, 2, 2, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('AH Nasi Goreng', 'AH Nasi Goreng', 'Albert Heijn', 'Supermarket', 'albert_heijn', NULL, 'snack', 350, '350g', 155, 7, 20, 5, 1, 1, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('AH Bami Goreng', 'AH Bami Goreng', 'Albert Heijn', 'Supermarket', 'albert_heijn', NULL, 'snack', 350, '350g', 150, 6, 21, 4, 1, 1, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('AH Boerenkoolstamppot', 'AH Boerenkoolstamppot', 'Albert Heijn', 'Supermarket', 'albert_heijn', NULL, 'snack', 400, '400g', 110, 8, 14, 3, 3, 1, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('AH Hutspot', 'AH Hutspot', 'Albert Heijn', 'Supermarket', 'albert_heijn', NULL, 'snack', 400, '400g', 95, 6, 16, 2, 2, 1, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('AH Sushi Zalm', 'AH Sushi Zalm', 'Albert Heijn', 'Supermarket', 'albert_heijn', NULL, 'snack', 180, '180g', 180, 12, 18, 6, 2, 1, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('AH Sushi Tonijn', 'AH Sushi Tonijn', 'Albert Heijn', 'Supermarket', 'albert_heijn', NULL, 'snack', 180, '180g', 165, 14, 18, 4, 2, 1, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('AH Sushi Vegetarisch', 'AH Sushi Vegetarisch', 'Albert Heijn', 'Supermarket', 'albert_heijn', NULL, 'snack', 180, '180g', 130, 3, 28, 1, 3, 2, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('AH Wrap Kip', 'AH Wrap Kip', 'Albert Heijn', 'Supermarket', 'albert_heijn', NULL, 'snack', 220, '220g', 220, 16, 20, 8, 2, 2, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('AH Wrap Tonijn', 'AH Wrap Tonijn', 'Albert Heijn', 'Supermarket', 'albert_heijn', NULL, 'snack', 220, '220g', 210, 15, 20, 8, 2, 1, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('AH Wrap Groente', 'AH Wrap Groente', 'Albert Heijn', 'Supermarket', 'albert_heijn', NULL, 'snack', 220, '220g', 180, 5, 25, 6, 3, 2, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('AH Kipsoep', 'AH Kipsoep', 'Albert Heijn', 'Supermarket', 'albert_heijn', NULL, 'snack', 200, '200ml', 50, 6, 5, 1, 1, 1, true);

-- VEGAN / PLANTAARDIG (30 products)
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Tofu Naturel', 'Tofu Naturel', 'AH', 'Supermarket', 'albert_heijn', NULL, 'proteinen', 100, '100g', 76, 8.1, 1.9, 4.8, 1.2, 0.2, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Tofu Gerookt', 'Tofu Gerookt', 'AH', 'Supermarket', 'albert_heijn', NULL, 'proteinen', 100, '100g', 180, 18, 7, 11, 2, 1, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Silken Tofu', 'Silken Tofu', 'AH', 'Supermarket', 'albert_heijn', NULL, 'proteinen', 100, '100g', 55, 6, 2, 3, 0, 0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Tempeh', 'Tempeh', 'AH', 'Supermarket', 'albert_heijn', NULL, 'proteinen', 100, '100g', 195, 19, 7, 11, 0, 0, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Seitan', 'Seitan', 'AH', 'Supermarket', 'albert_heijn', NULL, 'proteinen', 100, '100g', 110, 25, 2, 0.5, 0, 0, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Beyond Meat Burger', 'Beyond Meat Burger', 'Beyond Meat', 'Sports', 'beyond_meat', NULL, 'proteinen', 113, '113g', 250, 20, 5, 18, 2, 0, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Beyond Meat Worst', 'Beyond Meat Worst', 'Beyond Meat', 'Sports', 'beyond_meat', NULL, 'proteinen', 100, '100g', 270, 23, 4, 19, 2, 0, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Vivera Schnitzel', 'Vivera Schnitzel', 'Vivera', 'Supermarket', 'albert_heijn', NULL, 'proteinen', 100, '100g', 210, 18, 12, 10, 2, 1, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Vivera Burger', 'Vivera Burger', 'Vivera', 'Supermarket', 'albert_heijn', NULL, 'proteinen', 100, '100g', 200, 17, 11, 9, 2, 1, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Vivera Gehakt', 'Vivera Gehakt', 'Vivera', 'Supermarket', 'albert_heijn', NULL, 'proteinen', 100, '100g', 165, 15, 8, 8, 2, 0, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('De Vegetarische Slager Kipstukjes', 'De Vegetarische Slager Kipstukjes', 'Vegetarische Slager', 'Supermarket', 'albert_heijn', NULL, 'proteinen', 100, '100g', 150, 16, 4, 7, 1, 0, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('De Vegetarische Slager Shoarma', 'De Vegetarische Slager Shoarma', 'Vegetarische Slager', 'Supermarket', 'albert_heijn', NULL, 'proteinen', 100, '100g', 160, 15, 6, 8, 1, 0, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('De Vegetarische Slager Braadworst', 'De Vegetarische Slager Braadworst', 'Vegetarische Slager', 'Supermarket', 'albert_heijn', NULL, 'proteinen', 100, '100g', 220, 18, 7, 13, 2, 0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('De Vegetarische Slager Gehakt', 'De Vegetarische Slager Gehakt', 'Vegetarische Slager', 'Supermarket', 'albert_heijn', NULL, 'proteinen', 100, '100g', 175, 14, 8, 9, 2, 0, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Hummus', 'Hummus', 'AH', 'Supermarket', 'albert_heijn', NULL, 'saus', 100, '100g', 160, 5, 13, 9, 3, 1, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Edamame Diepvries', 'Edamame Diepvries', 'AH', 'Supermarket', 'albert_heijn', NULL, 'groente', 100, '100g', 111, 11, 10, 5, 6, 2, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Alpro Sojayoghurt Naturel', 'Alpro Sojayoghurt Naturel', 'Alpro', 'Supermarket', 'albert_heijn', NULL, 'zuivel', 125, '125ml', 45, 3.5, 0.5, 1.8, 0, 0, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Alpro Kokosyoghurt', 'Alpro Kokosyoghurt', 'Alpro', 'Supermarket', 'albert_heijn', NULL, 'zuivel', 125, '125ml', 80, 1.5, 7, 4, 0, 4, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Alpro Amandelyoghurt', 'Alpro Amandelyoghurt', 'Alpro', 'Supermarket', 'albert_heijn', NULL, 'zuivel', 125, '125ml', 50, 2, 1, 2, 0, 0, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Violife Kaas Cheddar', 'Violife Kaas Cheddar', 'Violife', 'Supermarket', 'albert_heijn', NULL, 'zuivel', 25, '25g', 360, 6, 1, 31, 0, 0, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Nurishh Kaas Mozzarella', 'Nurishh Kaas Mozzarella', 'Nurishh', 'Supermarket', 'albert_heijn', NULL, 'zuivel', 25, '25g', 280, 7, 2, 22, 0, 0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Nutritional Yeast Flakes', 'Nutritional Yeast Flakes', 'AH', 'Supermarket', 'albert_heijn', NULL, 'supplement', 5, '5g', 330, 50, 35, 7, 8, 0, false);

-- ONTBIJT EXTRAS (20 products)
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Aardbeijam', 'Aardbeijam', 'AH', 'Supermarket', 'albert_heijn', NULL, 'saus', 20, '20g', 260, 0.5, 65, 0, 1, 62, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Abrikozenjam', 'Abrikozenjam', 'AH', 'Supermarket', 'albert_heijn', NULL, 'saus', 20, '20g', 250, 0.5, 63, 0, 1, 60, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Appelstroop', 'Appelstroop', 'AH', 'Supermarket', 'albert_heijn', NULL, 'saus', 20, '20g', 200, 0, 50, 0, 1, 45, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Nutella Chocoladepasta', 'Nutella Chocoladepasta', 'Ferrero', 'Supermarket', 'albert_heijn', NULL, 'saus', 20, '20g', 540, 7, 57, 32, 3, 53, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('AH Chocoladepasta', 'AH Chocoladepasta', 'Albert Heijn', 'Supermarket', 'albert_heijn', NULL, 'saus', 20, '20g', 520, 6, 59, 30, 3, 52, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('De Ruijter Hagelslag Melk', 'De Ruijter Hagelslag Melk', 'De Ruijter', 'Supermarket', 'albert_heijn', NULL, 'saus', 20, '20g', 505, 6, 62, 24, 0, 55, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('De Ruijter Hagelslag Puur', 'De Ruijter Hagelslag Puur', 'De Ruijter', 'Supermarket', 'albert_heijn', NULL, 'saus', 20, '20g', 495, 8, 60, 26, 2, 50, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Lotus Speculoospasta', 'Lotus Speculoospasta', 'Lotus', 'Supermarket', 'albert_heijn', NULL, 'saus', 20, '20g', 510, 9, 58, 28, 2, 48, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Stroop', 'Stroop', 'AH', 'Supermarket', 'albert_heijn', NULL, 'saus', 15, '15g', 285, 0, 71, 0, 0, 70, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Granola Basis', 'Granola Basis', 'AH', 'Supermarket', 'albert_heijn', NULL, 'granen', 50, '50g', 480, 10, 60, 20, 8, 28, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Granola Honing Noten', 'Granola Honing Noten', 'Nature Valley', 'Supermarket', 'albert_heijn', NULL, 'granen', 50, '50g', 490, 12, 58, 22, 7, 26, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Granola Fruit', 'Granola Fruit', 'AH', 'Supermarket', 'albert_heijn', NULL, 'granen', 50, '50g', 470, 9, 62, 18, 6, 32, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Granola Chocolade', 'Granola Chocolade', 'Nature Valley', 'Supermarket', 'albert_heijn', NULL, 'granen', 50, '50g', 510, 11, 56, 26, 6, 34, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Granola Kokos', 'Granola Kokos', 'AH', 'Supermarket', 'albert_heijn', NULL, 'granen', 50, '50g', 495, 10, 58, 24, 8, 30, true);

-- MEER ZUIVEL specifiek (20 products)
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Hüttenkäse Zuivelhoeve', 'Hüttenkäse Zuivelhoeve', 'Zuivelhoeve', 'Supermarket', 'albert_heijn', NULL, 'zuivel', 125, '125ml', 102, 11, 4, 5, 0, 2, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Hüttenkäse AH', 'Hüttenkäse AH', 'Albert Heijn', 'Supermarket', 'albert_heijn', NULL, 'zuivel', 125, '125ml', 98, 10, 3, 5, 0, 2, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Skyr Naturel', 'Skyr Naturel', 'AH', 'Supermarket', 'albert_heijn', NULL, 'zuivel', 100, '100g', 60, 10, 3, 0.4, 0, 2, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Skyr Vanille', 'Skyr Vanille', 'AH', 'Supermarket', 'albert_heijn', NULL, 'zuivel', 100, '100g', 75, 10, 7, 0.5, 0, 6, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Skyr Aardbei', 'Skyr Aardbei', 'AH', 'Supermarket', 'albert_heijn', NULL, 'zuivel', 100, '100g', 72, 10, 6, 0.5, 0, 5, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Proteïne Pudding Ehrmann', 'Proteïne Pudding Ehrmann', 'Ehrmann', 'Supermarket', 'albert_heijn', NULL, 'zuivel', 200, '200g', 100, 12, 10, 2, 0, 7, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Proteïne Pudding Melkunie', 'Proteïne Pudding Melkunie', 'Melkunie', 'Supermarket', 'albert_heijn', NULL, 'zuivel', 200, '200g', 105, 13, 9, 2, 0, 6, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Drinkontbijt Vifit', 'Drinkontbijt Vifit', 'Vifit', 'Supermarket', 'albert_heijn', NULL, 'dranken', 250, '250ml', 68, 5, 8, 2, 0, 7, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Drinkontbijt Koffie', 'Drinkontbijt Koffie', 'Melkunie', 'Supermarket', 'albert_heijn', NULL, 'dranken', 250, '250ml', 65, 4, 10, 1.5, 0, 8, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Hertogshoorn IJsje', 'Hertogshoorn IJsje', 'Hertog', 'Supermarket', 'albert_heijn', NULL, 'snack', 40, '40g', 220, 3, 20, 14, 0, 18, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Magnum Ijs Classic', 'Magnum Ijs Classic', 'Magnum', 'Supermarket', 'albert_heijn', NULL, 'snack', 120, '120ml', 300, 4, 25, 21, 0, 21, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Magnum Ijs Almonds', 'Magnum Ijs Almonds', 'Magnum', 'Supermarket', 'albert_heijn', NULL, 'snack', 120, '120ml', 315, 5, 24, 23, 2, 20, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Cornetto Ijs Vanilla', 'Cornetto Ijs Vanilla', 'Cornetto', 'Supermarket', 'albert_heijn', NULL, 'snack', 120, '120ml', 250, 3, 28, 13, 0, 24, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Cornetto Ijs Stracciatella', 'Cornetto Ijs Stracciatella', 'Cornetto', 'Supermarket', 'albert_heijn', NULL, 'snack', 120, '120ml', 260, 3, 30, 14, 0, 26, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('AH Ijs Vanille', 'AH Ijs Vanille', 'Albert Heijn', 'Supermarket', 'albert_heijn', NULL, 'snack', 100, '100g', 210, 3, 22, 12, 0, 19, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('AH Ijs Chocolade', 'AH Ijs Chocolade', 'Albert Heijn', 'Supermarket', 'albert_heijn', NULL, 'snack', 100, '100g', 230, 3, 24, 14, 1, 21, true);

-- MEER VIS & SEAFOOD (15 products)
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Surimi Krabsticks', 'Surimi Krabsticks', 'AH', 'Supermarket', 'albert_heijn', NULL, 'vis', 100, '100g', 99, 12, 7, 3, 0, 6, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Tonijnsalade AH', 'Tonijnsalade AH', 'Albert Heijn', 'Supermarket', 'albert_heijn', NULL, 'vis', 200, '200g', 165, 16, 5, 8, 2, 1, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Zalmsalade', 'Zalmsalade', 'AH', 'Supermarket', 'albert_heijn', NULL, 'vis', 200, '200g', 185, 18, 4, 10, 2, 1, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Gerookte Heilbot', 'Gerookte Heilbot', 'AH', 'Supermarket', 'albert_heijn', NULL, 'vis', 100, '100g', 120, 24, 0, 3, 0, 0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Ansjovis', 'Ansjovis', 'Flota', 'Supermarket', 'albert_heijn', NULL, 'vis', 20, '20g', 200, 29, 0, 9, 0, 0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Inktvis', 'Inktvis', 'AH', 'Supermarket', 'albert_heijn', NULL, 'vis', 100, '100g', 92, 17, 3, 1.5, 0, 0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Kreeft Bevroren', 'Kreeft Bevroren', 'AH', 'Supermarket', 'albert_heijn', NULL, 'vis', 100, '100g', 95, 20, 0, 1, 0, 0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Visvingers', 'Visvingers', 'AH', 'Supermarket', 'albert_heijn', NULL, 'vis', 100, '100g', 195, 14, 16, 8, 0, 1, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Kabeljauw Filet', 'Kabeljauw Filet', 'AH', 'Supermarket', 'albert_heijn', NULL, 'vis', 100, '100g', 82, 18, 0, 1, 0, 0, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Mosselen', 'Mosselen', 'AH', 'Supermarket', 'albert_heijn', NULL, 'vis', 100, '100g', 95, 14, 7, 2, 0, 0, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Oesters', 'Oesters', 'AH', 'Supermarket', 'albert_heijn', NULL, 'vis', 100, '100g', 68, 14, 7, 1, 0, 0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Garnalen Diepvries', 'Garnalen Diepvries', 'AH', 'Supermarket', 'albert_heijn', NULL, 'vis', 100, '100g', 99, 24, 0, 0.5, 0, 0, true);

-- KRUIDEN & SPECERIJEN (15 products) - category='saus'
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Knoflookpoeder', 'Knoflookpoeder', 'AH', 'Supermarket', 'albert_heijn', NULL, 'saus', 2, '2g', 345, 17, 75, 0.5, 10, 1, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Uienpoeder', 'Uienpoeder', 'AH', 'Supermarket', 'albert_heijn', NULL, 'saus', 2, '2g', 340, 14, 76, 1, 8, 2, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Paprikapoeder', 'Paprikapoeder', 'AH', 'Supermarket', 'albert_heijn', NULL, 'saus', 2, '2g', 320, 12, 65, 13, 25, 9, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Cayennepeper', 'Cayennepeper', 'AH', 'Supermarket', 'albert_heijn', NULL, 'saus', 1, '1g', 320, 12, 64, 13, 25, 8, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Komijn', 'Komijn', 'AH', 'Supermarket', 'albert_heijn', NULL, 'saus', 2, '2g', 375, 18, 43, 22, 11, 2, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Kurkuma', 'Kurkuma', 'AH', 'Supermarket', 'albert_heijn', NULL, 'saus', 2, '2g', 355, 10, 65, 10, 21, 3, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Kaneel', 'Kaneel', 'AH', 'Supermarket', 'albert_heijn', NULL, 'saus', 2, '2g', 247, 4, 81, 3, 53, 0, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Oregano', 'Oregano', 'AH', 'Supermarket', 'albert_heijn', NULL, 'saus', 2, '2g', 265, 9, 69, 4, 42, 0, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Basilicum', 'Basilicum', 'AH', 'Supermarket', 'albert_heijn', NULL, 'saus', 2, '2g', 270, 27, 49, 6, 37, 0, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Tijm', 'Tijm', 'AH', 'Supermarket', 'albert_heijn', NULL, 'saus', 2, '2g', 276, 10, 64, 7, 48, 0, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Zwarte Peper Gemalen', 'Zwarte Peper Gemalen', 'AH', 'Supermarket', 'albert_heijn', NULL, 'saus', 2, '2g', 251, 10, 64, 3, 25, 0, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Zeezout', 'Zeezout', 'AH', 'Supermarket', 'albert_heijn', NULL, 'saus', 1, '1g', 0, 0, 0, 0, 0, 0, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Bouillonblokje Knorr Rund', 'Bouillonblokje Knorr Rund', 'Knorr', 'Supermarket', 'albert_heijn', NULL, 'saus', 10, '10g', 170, 28, 12, 2, 1, 2, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Bouillonblokje Maggi Kip', 'Bouillonblokje Maggi Kip', 'Maggi', 'Supermarket', 'albert_heijn', NULL, 'saus', 10, '10g', 165, 26, 14, 2, 0, 3, true);

-- MEER DRANKEN (20 products) - category='dranken'
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Heineken 0.0', 'Heineken 0.0', 'Heineken', 'Alcoholvrij', 'albert_heijn', NULL, 'dranken', 330, '330ml', 29, 0.4, 2.5, 0, 0, 0, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Bavaria 0.0', 'Bavaria 0.0', 'Bavaria', 'Alcoholvrij', 'albert_heijn', NULL, 'dranken', 330, '330ml', 28, 0.3, 2, 0, 0, 0, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Jupiler 0.0', 'Jupiler 0.0', 'Jupiler', 'Alcoholvrij', 'albert_heijn', NULL, 'dranken', 330, '330ml', 25, 0, 2, 0, 0, 0, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Kombucha Origineel', 'Kombucha Origineel', 'Remedy', 'Supermarket', 'albert_heijn', NULL, 'dranken', 250, '250ml', 14, 0, 2, 0, 0, 1.5, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Arizona Ijsthee', 'Arizona Ijsthee', 'Arizona', 'Supermarket', 'albert_heijn', NULL, 'dranken', 240, '240ml', 42, 0, 11, 0, 0, 10, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Lipton Ijsthee', 'Lipton Ijsthee', 'Lipton', 'Supermarket', 'albert_heijn', NULL, 'dranken', 250, '250ml', 32, 0, 8, 0, 0, 7.5, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Vers Geperst Sap', 'Vers Geperst Sap', 'AH', 'Supermarket', 'albert_heijn', NULL, 'dranken', 200, '200ml', 52, 0.5, 13, 0, 2, 11, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Tonic Schweppes', 'Tonic Schweppes', 'Schweppes', 'Supermarket', 'albert_heijn', NULL, 'dranken', 200, '200ml', 42, 0, 10.5, 0, 0, 9, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Tonic Fever-Tree', 'Tonic Fever-Tree', 'Fever-Tree', 'Supermarket', 'albert_heijn', NULL, 'dranken', 200, '200ml', 38, 0, 9.5, 0, 0, 8, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Ginger Beer Fever-Tree', 'Ginger Beer Fever-Tree', 'Fever-Tree', 'Supermarket', 'albert_heijn', NULL, 'dranken', 200, '200ml', 48, 0, 12, 0, 0, 11, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Ginger Ale', 'Ginger Ale', 'AH', 'Supermarket', 'albert_heijn', NULL, 'dranken', 200, '200ml', 36, 0, 9, 0, 0, 8, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Cider Appel', 'Cider Appel', 'Strongbow', 'Supermarket', 'albert_heijn', NULL, 'dranken', 440, '440ml', 42, 0, 4, 0, 0, 3, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Capri-Sun Appel', 'Capri-Sun Appel', 'Capri-Sun', 'Supermarket', 'albert_heijn', NULL, 'dranken', 200, '200ml', 47, 0, 11.5, 0, 0, 11, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Capri-Sun Bosvruchten', 'Capri-Sun Bosvruchten', 'Capri-Sun', 'Supermarket', 'albert_heijn', NULL, 'dranken', 200, '200ml', 46, 0, 11, 0, 0, 10.5, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Rivella Rood', 'Rivella Rood', 'Rivella', 'Supermarket', 'albert_heijn', NULL, 'dranken', 200, '200ml', 39, 0.2, 9.5, 0, 0, 9, false);

-- MEER SPORTS NUTRITION (30 products) - category='supplement'
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Bulk Powders Whey Protein', 'Bulk Powders Whey Protein', 'Bulk Powders', 'Sports', 'bulk_powders', NULL, 'supplement', 30, '30g', 120, 23, 2, 2, 0, 0, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Bulk Powders Creatine', 'Bulk Powders Creatine', 'Bulk Powders', 'Sports', 'bulk_powders', NULL, 'supplement', 5, '5g', 0, 0, 0, 0, 0, 0, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Bulk Powders Pre-Workout', 'Bulk Powders Pre-Workout', 'Bulk Powders', 'Sports', 'bulk_powders', NULL, 'supplement', 10, '10g', 37, 0.5, 9, 0, 0, 8, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Body & Fit Whey Isolate', 'Body & Fit Whey Isolate', 'Body & Fit', 'Sports', 'body_fit', NULL, 'supplement', 30, '30g', 118, 24, 1, 1, 0, 0, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Body & Fit Casein', 'Body & Fit Casein', 'Body & Fit', 'Sports', 'body_fit', NULL, 'supplement', 30, '30g', 115, 23, 1, 1, 0, 0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Body & Fit Protein Bar', 'Body & Fit Protein Bar', 'Body & Fit', 'Sports', 'body_fit', NULL, 'supplement', 50, '50g', 350, 20, 30, 12, 6, 14, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('226ERS Energy Gel', '226ERS Energy Gel', '226ERS', 'Sports', '226ers', NULL, 'supplement', 40, '40g', 270, 0, 67, 0, 0, 65, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('226ERS Recovery Drink', '226ERS Recovery Drink', '226ERS', 'Sports', '226ers', NULL, 'supplement', 50, '50g', 380, 24, 47, 3, 0, 25, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('SiS Energy Gel', 'SiS Energy Gel', 'Science in Sport', 'Sports', 'science_in_sport', NULL, 'supplement', 40, '40g', 260, 0, 65, 0, 0, 63, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('SiS Electrolyte', 'SiS Electrolyte', 'Science in Sport', 'Sports', 'science_in_sport', NULL, 'supplement', 20, '20g', 81, 0, 20, 0, 0, 18, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Powerbar Energy Gel', 'Powerbar Energy Gel', 'Powerbar', 'Sports', 'powerbar', NULL, 'supplement', 40, '40g', 275, 0, 68, 0, 0, 66, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Powerbar Bar', 'Powerbar Bar', 'Powerbar', 'Sports', 'powerbar', NULL, 'supplement', 65, '65g', 380, 10, 63, 8, 5, 35, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('PhD Smart Bar', 'PhD Smart Bar', 'PhD', 'Sports', 'phd', NULL, 'supplement', 65, '65g', 360, 18, 30, 14, 10, 12, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('PhD Protein Shake', 'PhD Protein Shake', 'PhD', 'Sports', 'phd', NULL, 'supplement', 30, '30g', 122, 24, 2, 2, 0, 0, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Mars Protein Bar', 'Mars Protein Bar', 'Mars', 'Sports', 'mars', NULL, 'supplement', 51, '51g', 380, 12, 47, 15, 6, 28, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Snickers Protein Bar', 'Snickers Protein Bar', 'Mars', 'Sports', 'mars', NULL, 'supplement', 47, '47g', 380, 12, 48, 15, 5, 32, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Milka Protein Bar', 'Milka Protein Bar', 'Mondelez', 'Sports', 'mondelez', NULL, 'supplement', 35, '35g', 385, 15, 40, 16, 5, 22, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('MyProtein Whey Isolate', 'MyProtein Whey Isolate', 'MyProtein', 'Sports', 'myprotein', NULL, 'supplement', 30, '30g', 120, 24, 1, 2, 0, 0, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('MyProtein Bar', 'MyProtein Bar', 'MyProtein', 'Sports', 'myprotein', NULL, 'supplement', 65, '65g', 360, 20, 32, 12, 7, 10, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Optimum Nutrition Whey', 'Optimum Nutrition Whey', 'Optimum Nutrition', 'Sports', 'on', NULL, 'supplement', 30, '30g', 120, 24, 1, 2, 0, 0, true);

-- MEER SNACKS (30 products)
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Protein Chips Zout Paprika', 'Protein Chips Zout Paprika', 'More Nutrition', 'Sports', 'more_nutrition', NULL, 'snack', 30, '30g', 480, 20, 42, 24, 8, 2, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Protein Chips Barbeque', 'Protein Chips Barbeque', 'ESN', 'Sports', 'esn', NULL, 'snack', 30, '30g', 475, 19, 44, 23, 7, 1, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Rice Cakes met Noten', 'Rice Cakes met Noten', 'AH', 'Supermarket', 'albert_heijn', NULL, 'snack', 25, '25g', 385, 10, 58, 12, 6, 8, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Rice Cakes met Chocolade', 'Rice Cakes met Chocolade', 'AH', 'Supermarket', 'albert_heijn', NULL, 'snack', 25, '25g', 410, 8, 62, 14, 4, 26, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Nakd Fruit Bar', 'Nakd Fruit Bar', 'Nakd', 'Supermarket', 'albert_heijn', NULL, 'snack', 35, '35g', 360, 6, 48, 15, 6, 32, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Trek Bar', 'Trek Bar', 'Trek', 'Supermarket', 'albert_heijn', NULL, 'snack', 40, '40g', 368, 8, 50, 14, 4, 30, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Bear Bar', 'Bear Bar', 'Bear', 'Supermarket', 'albert_heijn', NULL, 'snack', 35, '35g', 355, 5, 52, 13, 5, 38, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Energie Ballen Dadel', 'Energie Ballen Dadel', 'AH', 'Supermarket', 'albert_heijn', NULL, 'snack', 30, '30g', 320, 6, 52, 10, 6, 40, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Energie Ballen Chocolade', 'Energie Ballen Chocolade', 'AH', 'Supermarket', 'albert_heijn', NULL, 'snack', 30, '30g', 340, 8, 48, 14, 6, 36, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Nori Chips', 'Nori Chips', 'AH', 'Supermarket', 'albert_heijn', NULL, 'snack', 20, '20g', 200, 40, 5, 3, 8, 0, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Beef Jerky', 'Beef Jerky', 'Jack Links', 'Supermarket', 'albert_heijn', NULL, 'snack', 25, '25g', 300, 50, 5, 7, 0, 2, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Gedroogd Fruitenmix', 'Gedroogd Fruitenmix', 'AH', 'Supermarket', 'albert_heijn', NULL, 'snack', 30, '30g', 280, 2, 70, 1, 6, 55, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Trail Mix', 'Trail Mix', 'AH', 'Supermarket', 'albert_heijn', NULL, 'snack', 40, '40g', 480, 14, 42, 28, 8, 25, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Protein Cookies', 'Protein Cookies', 'Lenny & Larrys', 'Sports', 'lenny_larrys', NULL, 'snack', 40, '40g', 400, 16, 42, 16, 5, 18, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Rijstwafels Chocolade', 'Rijstwafels Chocolade', 'AH', 'Supermarket', 'albert_heijn', NULL, 'snack', 30, '30g', 385, 5, 62, 12, 3, 22, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Rijstwafels Yoghurt', 'Rijstwafels Yoghurt', 'AH', 'Supermarket', 'albert_heijn', NULL, 'snack', 30, '30g', 370, 6, 60, 11, 2, 20, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Crackers met Kaas', 'Crackers met Kaas', 'AH', 'Supermarket', 'albert_heijn', NULL, 'snack', 30, '30g', 420, 10, 44, 22, 2, 3, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Mini Kaasjes Babybel', 'Mini Kaasjes Babybel', 'Babybel', 'Supermarket', 'albert_heijn', NULL, 'snack', 20, '20g', 360, 24, 0, 30, 0, 0, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Seaweed Snack', 'Seaweed Snack', 'AH', 'Supermarket', 'albert_heijn', NULL, 'snack', 5, '5g', 180, 38, 6, 2, 10, 0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Gezonde Chips Biet', 'Gezonde Chips Biet', 'Beet Chips', 'Supermarket', 'albert_heijn', NULL, 'snack', 30, '30g', 340, 4, 58, 10, 8, 15, false);

-- MEER BROOD/BAKKERIJ (15 products)
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Eiwitbrood', 'Eiwitbrood', 'AH', 'Supermarket', 'albert_heijn', NULL, 'brood', 50, '50g', 250, 18, 10, 14, 8, 1, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Lijnzaadbrood', 'Lijnzaadbrood', 'AH', 'Supermarket', 'albert_heijn', NULL, 'brood', 50, '50g', 250, 10, 32, 8, 6, 2, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Speltbrood', 'Speltbrood', 'AH', 'Supermarket', 'albert_heijn', NULL, 'brood', 50, '50g', 260, 11, 45, 5, 7, 2, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Glutenvrij Brood Schär', 'Glutenvrij Brood Schär', 'Schär', 'Supermarket', 'albert_heijn', NULL, 'brood', 45, '45g', 280, 6, 48, 8, 5, 2, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Maïsbrood', 'Maïsbrood', 'AH', 'Supermarket', 'albert_heijn', NULL, 'brood', 50, '50g', 270, 8, 48, 6, 4, 1, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Cornbread', 'Cornbread', 'AH', 'Supermarket', 'albert_heijn', NULL, 'brood', 60, '60g', 290, 7, 50, 7, 3, 4, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Flatbread', 'Flatbread', 'AH', 'Supermarket', 'albert_heijn', NULL, 'brood', 30, '30g', 280, 8, 44, 7, 2, 1, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Lavash', 'Lavash', 'AH', 'Supermarket', 'albert_heijn', NULL, 'brood', 30, '30g', 260, 9, 48, 2, 2, 0, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Blini Boekweit', 'Blini Boekweit', 'AH', 'Supermarket', 'albert_heijn', NULL, 'brood', 30, '30g', 210, 6, 42, 2, 3, 0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Zuurdesembrood', 'Zuurdesembrood', 'AH', 'Supermarket', 'albert_heijn', NULL, 'brood', 50, '50g', 240, 9, 46, 2, 3, 1, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Roggbrood', 'Roggbrood', 'AH', 'Supermarket', 'albert_heijn', NULL, 'brood', 50, '50g', 220, 10, 42, 2, 7, 1, true);

-- INTERNATIONAAL/AZIATISCH (20 products)
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Sushi Rijst', 'Sushi Rijst', 'AH', 'Supermarket', 'albert_heijn', NULL, 'granen', 50, '50g', 170, 3, 37, 0.5, 0.5, 0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Miso Paste', 'Miso Paste', 'AH', 'Supermarket', 'albert_heijn', NULL, 'saus', 15, '15g', 140, 13, 6, 5, 1, 0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Tahini', 'Tahini', 'AH', 'Supermarket', 'albert_heijn', NULL, 'saus', 15, '15g', 595, 17, 21, 54, 10, 1, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Harissa Pasta', 'Harissa Pasta', 'AH', 'Supermarket', 'albert_heijn', NULL, 'saus', 10, '10g', 150, 5, 12, 9, 2, 1, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Sambal Oelek', 'Sambal Oelek', 'Conimex', 'Supermarket', 'albert_heijn', NULL, 'saus', 5, '5g', 80, 3, 10, 3, 2, 2, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Ketjap Manis', 'Ketjap Manis', 'Conimex', 'Supermarket', 'albert_heijn', NULL, 'saus', 15, '15ml', 190, 2, 42, 0, 0, 35, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Hoisin Saus', 'Hoisin Saus', 'AH', 'Supermarket', 'albert_heijn', NULL, 'saus', 15, '15ml', 140, 2, 25, 2, 1, 20, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Rijstpapier', 'Rijstpapier', 'AH', 'Supermarket', 'albert_heijn', NULL, 'granen', 10, '10g', 350, 8, 78, 0, 1, 0, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Wonton Vellen', 'Wonton Vellen', 'AH', 'Supermarket', 'albert_heijn', NULL, 'granen', 30, '30g', 295, 9, 54, 2, 2, 1, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Panko', 'Panko', 'AH', 'Supermarket', 'albert_heijn', NULL, 'granen', 15, '15g', 350, 10, 70, 2, 4, 0, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Kokosmelk Blik', 'Kokosmelk Blik', 'AH', 'Supermarket', 'albert_heijn', NULL, 'dranken', 100, '100ml', 200, 2, 5, 20, 0, 3, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Bami Blokken', 'Bami Blokken', 'AH', 'Supermarket', 'albert_heijn', NULL, 'granen', 30, '30g', 280, 8, 52, 2, 2, 1, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Gochujang Saus', 'Gochujang Saus', 'AH', 'Supermarket', 'albert_heijn', NULL, 'saus', 15, '15g', 100, 4, 18, 1, 2, 10, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Sriracha Saus', 'Sriracha Saus', 'AH', 'Supermarket', 'albert_heijn', NULL, 'saus', 5, '5g', 80, 2, 16, 0.5, 1, 10, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Tamari Saus', 'Tamari Saus', 'AH', 'Supermarket', 'albert_heijn', NULL, 'saus', 10, '10ml', 70, 11, 4, 0, 0, 2, false);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Sesamolie', 'Sesamolie', 'AH', 'Supermarket', 'albert_heijn', NULL, 'olie_vet', 10, '10ml', 880, 0, 0, 100, 0, 0, true);
INSERT INTO food_products (name, name_nl, brand, brand_category, source, barcode, category, serving_size_g, serving_label, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, sugar_per_100g, is_popular) VALUES ('Rijstazijn', 'Rijstazijn', 'AH', 'Supermarket', 'albert_heijn', NULL, 'saus', 15, '15ml', 18, 0, 0.8, 0, 0, 0, false);
