// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/auth/callback/invite" | "/auth/callback/recovery" | "/auth/reset-password" | "/auth/set-password" | "/auth/verify" | "/client" | "/client/accountability" | "/client/booking" | "/client/calendar" | "/client/check-in" | "/client/community" | "/client/exercises" | "/client/health" | "/client/journey" | "/client/meal-plan" | "/client/measurements" | "/client/messages" | "/client/notifications" | "/client/notifications/[id]" | "/client/nutrition" | "/client/profile" | "/client/profile/diet" | "/client/profile/edit" | "/client/profile/goals" | "/client/profile/health" | "/client/profile/help" | "/client/profile/invoices" | "/client/profile/notifications" | "/client/profile/privacy" | "/client/program" | "/client/progress" | "/client/prompts" | "/client/push-test" | "/client/resources" | "/client/stats" | "/client/supplements" | "/client/video" | "/client/video/[sessionId]" | "/client/weekly-check-in" | "/client/workout" | "/client/workout/active" | "/client/workout/complete" | "/client/workout/history" | "/coach" | "/coach/accountability" | "/coach/activity" | "/coach/ai-settings" | "/coach/billing" | "/coach/broadcasts" | "/coach/check-ins" | "/coach/check-ins/[id]" | "/coach/clients" | "/coach/clients/[id]" | "/coach/clients/[id]/intake" | "/coach/clients/[id]/meal-plan" | "/coach/clients/[id]/nutrition" | "/coach/clients/[id]/program" | "/coach/clients/[id]/progress" | "/coach/clients/[id]/report" | "/coach/clients/[id]/workout/[sessionId]" | "/coach/clients/new" | "/coach/community" | "/coach/exercises" | "/coach/exercises/[id]" | "/coach/exercises/new" | "/coach/messages" | "/coach/messages/[clientId]" | "/coach/nutrition" | "/coach/nutrition/[id]/edit" | "/coach/nutrition/new" | "/coach/programs" | "/coach/programs/[id]" | "/coach/programs/new" | "/coach/prompts" | "/coach/prompts/responses" | "/coach/resources" | "/coach/schedule" | "/coach/schedule/availability" | "/coach/video/[sessionId]" | "/offline" | "/onboarding"
type AppRouteHandlerRoutes = "/api/accountability" | "/api/accountability/coach" | "/api/ai-feedback" | "/api/ai-test" | "/api/auth/reset-password" | "/api/checkins" | "/api/client-program" | "/api/client-workout" | "/api/clients" | "/api/clients/resend-invite" | "/api/coach-badges" | "/api/coach-seen" | "/api/community" | "/api/community/comments" | "/api/community/like" | "/api/conversations/[clientId]/priority" | "/api/cron/accountability" | "/api/cron/ai-nudges" | "/api/cron/check-in-reminders" | "/api/cron/meeting-reminders" | "/api/cron/send-prompts" | "/api/cron/smart-suggestions" | "/api/cron/test" | "/api/cron/video-reminders" | "/api/cron/weekly-report" | "/api/dashboard" | "/api/exercises" | "/api/exercises/[id]" | "/api/food-search" | "/api/habits" | "/api/health-metrics" | "/api/meal-plans" | "/api/messages/[id]/read" | "/api/nutrition-log" | "/api/onboarding-status" | "/api/progress" | "/api/push" | "/api/push/send" | "/api/push/test" | "/api/reports" | "/api/reports/client/[clientId]" | "/api/reports/generate" | "/api/scheduling/availability" | "/api/stripe/customer-portal" | "/api/subscriptions/cancel" | "/api/subscriptions/create" | "/api/supplements" | "/api/training-phases" | "/api/video-sessions" | "/api/video-sessions/[id]" | "/api/webhooks/stripe" | "/api/weekly-check-in" | "/api/workout-complete" | "/api/workout-feedback" | "/api/workout-finish" | "/api/workout-save" | "/auth/callback"
type PageRoutes = never
type LayoutRoutes = "/" | "/client" | "/coach" | "/onboarding"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/accountability": {}
  "/api/accountability/coach": {}
  "/api/ai-feedback": {}
  "/api/ai-test": {}
  "/api/auth/reset-password": {}
  "/api/checkins": {}
  "/api/client-program": {}
  "/api/client-workout": {}
  "/api/clients": {}
  "/api/clients/resend-invite": {}
  "/api/coach-badges": {}
  "/api/coach-seen": {}
  "/api/community": {}
  "/api/community/comments": {}
  "/api/community/like": {}
  "/api/conversations/[clientId]/priority": { "clientId": string; }
  "/api/cron/accountability": {}
  "/api/cron/ai-nudges": {}
  "/api/cron/check-in-reminders": {}
  "/api/cron/meeting-reminders": {}
  "/api/cron/send-prompts": {}
  "/api/cron/smart-suggestions": {}
  "/api/cron/test": {}
  "/api/cron/video-reminders": {}
  "/api/cron/weekly-report": {}
  "/api/dashboard": {}
  "/api/exercises": {}
  "/api/exercises/[id]": { "id": string; }
  "/api/food-search": {}
  "/api/habits": {}
  "/api/health-metrics": {}
  "/api/meal-plans": {}
  "/api/messages/[id]/read": { "id": string; }
  "/api/nutrition-log": {}
  "/api/onboarding-status": {}
  "/api/progress": {}
  "/api/push": {}
  "/api/push/send": {}
  "/api/push/test": {}
  "/api/reports": {}
  "/api/reports/client/[clientId]": { "clientId": string; }
  "/api/reports/generate": {}
  "/api/scheduling/availability": {}
  "/api/stripe/customer-portal": {}
  "/api/subscriptions/cancel": {}
  "/api/subscriptions/create": {}
  "/api/supplements": {}
  "/api/training-phases": {}
  "/api/video-sessions": {}
  "/api/video-sessions/[id]": { "id": string; }
  "/api/webhooks/stripe": {}
  "/api/weekly-check-in": {}
  "/api/workout-complete": {}
  "/api/workout-feedback": {}
  "/api/workout-finish": {}
  "/api/workout-save": {}
  "/auth/callback": {}
  "/auth/callback/invite": {}
  "/auth/callback/recovery": {}
  "/auth/reset-password": {}
  "/auth/set-password": {}
  "/auth/verify": {}
  "/client": {}
  "/client/accountability": {}
  "/client/booking": {}
  "/client/calendar": {}
  "/client/check-in": {}
  "/client/community": {}
  "/client/exercises": {}
  "/client/health": {}
  "/client/journey": {}
  "/client/meal-plan": {}
  "/client/measurements": {}
  "/client/messages": {}
  "/client/notifications": {}
  "/client/notifications/[id]": { "id": string; }
  "/client/nutrition": {}
  "/client/profile": {}
  "/client/profile/diet": {}
  "/client/profile/edit": {}
  "/client/profile/goals": {}
  "/client/profile/health": {}
  "/client/profile/help": {}
  "/client/profile/invoices": {}
  "/client/profile/notifications": {}
  "/client/profile/privacy": {}
  "/client/program": {}
  "/client/progress": {}
  "/client/prompts": {}
  "/client/push-test": {}
  "/client/resources": {}
  "/client/stats": {}
  "/client/supplements": {}
  "/client/video": {}
  "/client/video/[sessionId]": { "sessionId": string; }
  "/client/weekly-check-in": {}
  "/client/workout": {}
  "/client/workout/active": {}
  "/client/workout/complete": {}
  "/client/workout/history": {}
  "/coach": {}
  "/coach/accountability": {}
  "/coach/activity": {}
  "/coach/ai-settings": {}
  "/coach/billing": {}
  "/coach/broadcasts": {}
  "/coach/check-ins": {}
  "/coach/check-ins/[id]": { "id": string; }
  "/coach/clients": {}
  "/coach/clients/[id]": { "id": string; }
  "/coach/clients/[id]/intake": { "id": string; }
  "/coach/clients/[id]/meal-plan": { "id": string; }
  "/coach/clients/[id]/nutrition": { "id": string; }
  "/coach/clients/[id]/program": { "id": string; }
  "/coach/clients/[id]/progress": { "id": string; }
  "/coach/clients/[id]/report": { "id": string; }
  "/coach/clients/[id]/workout/[sessionId]": { "id": string; "sessionId": string; }
  "/coach/clients/new": {}
  "/coach/community": {}
  "/coach/exercises": {}
  "/coach/exercises/[id]": { "id": string; }
  "/coach/exercises/new": {}
  "/coach/messages": {}
  "/coach/messages/[clientId]": { "clientId": string; }
  "/coach/nutrition": {}
  "/coach/nutrition/[id]/edit": { "id": string; }
  "/coach/nutrition/new": {}
  "/coach/programs": {}
  "/coach/programs/[id]": { "id": string; }
  "/coach/programs/new": {}
  "/coach/prompts": {}
  "/coach/prompts/responses": {}
  "/coach/resources": {}
  "/coach/schedule": {}
  "/coach/schedule/availability": {}
  "/coach/video/[sessionId]": { "sessionId": string; }
  "/offline": {}
  "/onboarding": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/client": never
  "/coach": never
  "/onboarding": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
