// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/auth/callback/invite/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/callback/invite">> = Specific
  const handler = {} as typeof import("../../src/app/auth/callback/invite/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/callback/recovery/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/callback/recovery">> = Specific
  const handler = {} as typeof import("../../src/app/auth/callback/recovery/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/reset-password">> = Specific
  const handler = {} as typeof import("../../src/app/auth/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/set-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/set-password">> = Specific
  const handler = {} as typeof import("../../src/app/auth/set-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/verify/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/verify">> = Specific
  const handler = {} as typeof import("../../src/app/auth/verify/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/client/accountability/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/client/accountability">> = Specific
  const handler = {} as typeof import("../../src/app/client/accountability/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/client/booking/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/client/booking">> = Specific
  const handler = {} as typeof import("../../src/app/client/booking/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/client/calendar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/client/calendar">> = Specific
  const handler = {} as typeof import("../../src/app/client/calendar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/client/check-in/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/client/check-in">> = Specific
  const handler = {} as typeof import("../../src/app/client/check-in/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/client/community/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/client/community">> = Specific
  const handler = {} as typeof import("../../src/app/client/community/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/client/exercises/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/client/exercises">> = Specific
  const handler = {} as typeof import("../../src/app/client/exercises/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/client/health/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/client/health">> = Specific
  const handler = {} as typeof import("../../src/app/client/health/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/client/journey/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/client/journey">> = Specific
  const handler = {} as typeof import("../../src/app/client/journey/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/client/meal-plan/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/client/meal-plan">> = Specific
  const handler = {} as typeof import("../../src/app/client/meal-plan/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/client/measurements/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/client/measurements">> = Specific
  const handler = {} as typeof import("../../src/app/client/measurements/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/client/messages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/client/messages">> = Specific
  const handler = {} as typeof import("../../src/app/client/messages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/client/notifications/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/client/notifications/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/client/notifications/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/client/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/client/notifications">> = Specific
  const handler = {} as typeof import("../../src/app/client/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/client/nutrition/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/client/nutrition">> = Specific
  const handler = {} as typeof import("../../src/app/client/nutrition/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/client/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/client">> = Specific
  const handler = {} as typeof import("../../src/app/client/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/client/profile/diet/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/client/profile/diet">> = Specific
  const handler = {} as typeof import("../../src/app/client/profile/diet/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/client/profile/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/client/profile/edit">> = Specific
  const handler = {} as typeof import("../../src/app/client/profile/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/client/profile/goals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/client/profile/goals">> = Specific
  const handler = {} as typeof import("../../src/app/client/profile/goals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/client/profile/health/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/client/profile/health">> = Specific
  const handler = {} as typeof import("../../src/app/client/profile/health/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/client/profile/help/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/client/profile/help">> = Specific
  const handler = {} as typeof import("../../src/app/client/profile/help/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/client/profile/invoices/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/client/profile/invoices">> = Specific
  const handler = {} as typeof import("../../src/app/client/profile/invoices/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/client/profile/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/client/profile/notifications">> = Specific
  const handler = {} as typeof import("../../src/app/client/profile/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/client/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/client/profile">> = Specific
  const handler = {} as typeof import("../../src/app/client/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/client/profile/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/client/profile/privacy">> = Specific
  const handler = {} as typeof import("../../src/app/client/profile/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/client/program/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/client/program">> = Specific
  const handler = {} as typeof import("../../src/app/client/program/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/client/progress/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/client/progress">> = Specific
  const handler = {} as typeof import("../../src/app/client/progress/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/client/prompts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/client/prompts">> = Specific
  const handler = {} as typeof import("../../src/app/client/prompts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/client/push-test/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/client/push-test">> = Specific
  const handler = {} as typeof import("../../src/app/client/push-test/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/client/resources/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/client/resources">> = Specific
  const handler = {} as typeof import("../../src/app/client/resources/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/client/stats/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/client/stats">> = Specific
  const handler = {} as typeof import("../../src/app/client/stats/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/client/supplements/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/client/supplements">> = Specific
  const handler = {} as typeof import("../../src/app/client/supplements/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/client/video/[sessionId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/client/video/[sessionId]">> = Specific
  const handler = {} as typeof import("../../src/app/client/video/[sessionId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/client/video/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/client/video">> = Specific
  const handler = {} as typeof import("../../src/app/client/video/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/client/weekly-check-in/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/client/weekly-check-in">> = Specific
  const handler = {} as typeof import("../../src/app/client/weekly-check-in/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/client/workout/active/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/client/workout/active">> = Specific
  const handler = {} as typeof import("../../src/app/client/workout/active/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/client/workout/complete/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/client/workout/complete">> = Specific
  const handler = {} as typeof import("../../src/app/client/workout/complete/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/client/workout/history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/client/workout/history">> = Specific
  const handler = {} as typeof import("../../src/app/client/workout/history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/client/workout/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/client/workout">> = Specific
  const handler = {} as typeof import("../../src/app/client/workout/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/coach/accountability/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/coach/accountability">> = Specific
  const handler = {} as typeof import("../../src/app/coach/accountability/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/coach/activity/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/coach/activity">> = Specific
  const handler = {} as typeof import("../../src/app/coach/activity/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/coach/ai-settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/coach/ai-settings">> = Specific
  const handler = {} as typeof import("../../src/app/coach/ai-settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/coach/billing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/coach/billing">> = Specific
  const handler = {} as typeof import("../../src/app/coach/billing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/coach/broadcasts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/coach/broadcasts">> = Specific
  const handler = {} as typeof import("../../src/app/coach/broadcasts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/coach/check-ins/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/coach/check-ins/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/coach/check-ins/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/coach/check-ins/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/coach/check-ins">> = Specific
  const handler = {} as typeof import("../../src/app/coach/check-ins/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/coach/clients/[id]/intake/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/coach/clients/[id]/intake">> = Specific
  const handler = {} as typeof import("../../src/app/coach/clients/[id]/intake/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/coach/clients/[id]/meal-plan/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/coach/clients/[id]/meal-plan">> = Specific
  const handler = {} as typeof import("../../src/app/coach/clients/[id]/meal-plan/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/coach/clients/[id]/nutrition/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/coach/clients/[id]/nutrition">> = Specific
  const handler = {} as typeof import("../../src/app/coach/clients/[id]/nutrition/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/coach/clients/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/coach/clients/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/coach/clients/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/coach/clients/[id]/program/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/coach/clients/[id]/program">> = Specific
  const handler = {} as typeof import("../../src/app/coach/clients/[id]/program/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/coach/clients/[id]/progress/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/coach/clients/[id]/progress">> = Specific
  const handler = {} as typeof import("../../src/app/coach/clients/[id]/progress/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/coach/clients/[id]/report/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/coach/clients/[id]/report">> = Specific
  const handler = {} as typeof import("../../src/app/coach/clients/[id]/report/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/coach/clients/[id]/workout/[sessionId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/coach/clients/[id]/workout/[sessionId]">> = Specific
  const handler = {} as typeof import("../../src/app/coach/clients/[id]/workout/[sessionId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/coach/clients/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/coach/clients/new">> = Specific
  const handler = {} as typeof import("../../src/app/coach/clients/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/coach/clients/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/coach/clients">> = Specific
  const handler = {} as typeof import("../../src/app/coach/clients/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/coach/community/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/coach/community">> = Specific
  const handler = {} as typeof import("../../src/app/coach/community/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/coach/exercises/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/coach/exercises/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/coach/exercises/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/coach/exercises/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/coach/exercises/new">> = Specific
  const handler = {} as typeof import("../../src/app/coach/exercises/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/coach/exercises/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/coach/exercises">> = Specific
  const handler = {} as typeof import("../../src/app/coach/exercises/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/coach/messages/[clientId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/coach/messages/[clientId]">> = Specific
  const handler = {} as typeof import("../../src/app/coach/messages/[clientId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/coach/messages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/coach/messages">> = Specific
  const handler = {} as typeof import("../../src/app/coach/messages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/coach/nutrition/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/coach/nutrition/[id]/edit">> = Specific
  const handler = {} as typeof import("../../src/app/coach/nutrition/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/coach/nutrition/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/coach/nutrition/new">> = Specific
  const handler = {} as typeof import("../../src/app/coach/nutrition/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/coach/nutrition/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/coach/nutrition">> = Specific
  const handler = {} as typeof import("../../src/app/coach/nutrition/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/coach/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/coach">> = Specific
  const handler = {} as typeof import("../../src/app/coach/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/coach/programs/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/coach/programs/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/coach/programs/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/coach/programs/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/coach/programs/new">> = Specific
  const handler = {} as typeof import("../../src/app/coach/programs/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/coach/programs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/coach/programs">> = Specific
  const handler = {} as typeof import("../../src/app/coach/programs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/coach/prompts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/coach/prompts">> = Specific
  const handler = {} as typeof import("../../src/app/coach/prompts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/coach/prompts/responses/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/coach/prompts/responses">> = Specific
  const handler = {} as typeof import("../../src/app/coach/prompts/responses/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/coach/resources/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/coach/resources">> = Specific
  const handler = {} as typeof import("../../src/app/coach/resources/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/coach/schedule/availability/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/coach/schedule/availability">> = Specific
  const handler = {} as typeof import("../../src/app/coach/schedule/availability/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/coach/schedule/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/coach/schedule">> = Specific
  const handler = {} as typeof import("../../src/app/coach/schedule/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/coach/video/[sessionId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/coach/video/[sessionId]">> = Specific
  const handler = {} as typeof import("../../src/app/coach/video/[sessionId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/offline/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/offline">> = Specific
  const handler = {} as typeof import("../../src/app/offline/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/onboarding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/onboarding">> = Specific
  const handler = {} as typeof import("../../src/app/onboarding/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/accountability/coach/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/accountability/coach">> = Specific
  const handler = {} as typeof import("../../src/app/api/accountability/coach/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/accountability/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/accountability">> = Specific
  const handler = {} as typeof import("../../src/app/api/accountability/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai-feedback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai-feedback">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai-feedback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai-test/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai-test">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai-test/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/reset-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/reset-password">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/reset-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/checkins/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/checkins">> = Specific
  const handler = {} as typeof import("../../src/app/api/checkins/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/client-program/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/client-program">> = Specific
  const handler = {} as typeof import("../../src/app/api/client-program/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/client-workout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/client-workout">> = Specific
  const handler = {} as typeof import("../../src/app/api/client-workout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/clients/resend-invite/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/clients/resend-invite">> = Specific
  const handler = {} as typeof import("../../src/app/api/clients/resend-invite/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/clients/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/clients">> = Specific
  const handler = {} as typeof import("../../src/app/api/clients/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/coach-badges/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/coach-badges">> = Specific
  const handler = {} as typeof import("../../src/app/api/coach-badges/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/coach-seen/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/coach-seen">> = Specific
  const handler = {} as typeof import("../../src/app/api/coach-seen/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/community/comments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/community/comments">> = Specific
  const handler = {} as typeof import("../../src/app/api/community/comments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/community/like/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/community/like">> = Specific
  const handler = {} as typeof import("../../src/app/api/community/like/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/community/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/community">> = Specific
  const handler = {} as typeof import("../../src/app/api/community/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/conversations/[clientId]/priority/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/conversations/[clientId]/priority">> = Specific
  const handler = {} as typeof import("../../src/app/api/conversations/[clientId]/priority/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/accountability/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/accountability">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/accountability/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/ai-nudges/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/ai-nudges">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/ai-nudges/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/check-in-reminders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/check-in-reminders">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/check-in-reminders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/meeting-reminders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/meeting-reminders">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/meeting-reminders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/send-prompts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/send-prompts">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/send-prompts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/smart-suggestions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/smart-suggestions">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/smart-suggestions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/test/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/test">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/test/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/video-reminders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/video-reminders">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/video-reminders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/weekly-report/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/weekly-report">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/weekly-report/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dashboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/api/dashboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/exercises/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exercises/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/exercises/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/exercises/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exercises">> = Specific
  const handler = {} as typeof import("../../src/app/api/exercises/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/food-search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/food-search">> = Specific
  const handler = {} as typeof import("../../src/app/api/food-search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/habits/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/habits">> = Specific
  const handler = {} as typeof import("../../src/app/api/habits/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/health-metrics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health-metrics">> = Specific
  const handler = {} as typeof import("../../src/app/api/health-metrics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/meal-plans/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/meal-plans">> = Specific
  const handler = {} as typeof import("../../src/app/api/meal-plans/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/messages/[id]/read/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/messages/[id]/read">> = Specific
  const handler = {} as typeof import("../../src/app/api/messages/[id]/read/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/nutrition-log/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/nutrition-log">> = Specific
  const handler = {} as typeof import("../../src/app/api/nutrition-log/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/onboarding-status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/onboarding-status">> = Specific
  const handler = {} as typeof import("../../src/app/api/onboarding-status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/progress/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/progress">> = Specific
  const handler = {} as typeof import("../../src/app/api/progress/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/push/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/push">> = Specific
  const handler = {} as typeof import("../../src/app/api/push/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/push/send/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/push/send">> = Specific
  const handler = {} as typeof import("../../src/app/api/push/send/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/push/test/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/push/test">> = Specific
  const handler = {} as typeof import("../../src/app/api/push/test/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/reports/client/[clientId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reports/client/[clientId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/reports/client/[clientId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/reports/generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reports/generate">> = Specific
  const handler = {} as typeof import("../../src/app/api/reports/generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/reports/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reports">> = Specific
  const handler = {} as typeof import("../../src/app/api/reports/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/scheduling/availability/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/scheduling/availability">> = Specific
  const handler = {} as typeof import("../../src/app/api/scheduling/availability/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/stripe/customer-portal/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stripe/customer-portal">> = Specific
  const handler = {} as typeof import("../../src/app/api/stripe/customer-portal/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/subscriptions/cancel/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/subscriptions/cancel">> = Specific
  const handler = {} as typeof import("../../src/app/api/subscriptions/cancel/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/subscriptions/create/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/subscriptions/create">> = Specific
  const handler = {} as typeof import("../../src/app/api/subscriptions/create/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/supplements/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/supplements">> = Specific
  const handler = {} as typeof import("../../src/app/api/supplements/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/training-phases/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/training-phases">> = Specific
  const handler = {} as typeof import("../../src/app/api/training-phases/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/video-sessions/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/video-sessions/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/video-sessions/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/video-sessions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/video-sessions">> = Specific
  const handler = {} as typeof import("../../src/app/api/video-sessions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/webhooks/stripe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/stripe">> = Specific
  const handler = {} as typeof import("../../src/app/api/webhooks/stripe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/weekly-check-in/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/weekly-check-in">> = Specific
  const handler = {} as typeof import("../../src/app/api/weekly-check-in/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/workout-complete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/workout-complete">> = Specific
  const handler = {} as typeof import("../../src/app/api/workout-complete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/workout-feedback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/workout-feedback">> = Specific
  const handler = {} as typeof import("../../src/app/api/workout-feedback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/workout-finish/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/workout-finish">> = Specific
  const handler = {} as typeof import("../../src/app/api/workout-finish/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/workout-save/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/workout-save">> = Specific
  const handler = {} as typeof import("../../src/app/api/workout-save/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/callback">> = Specific
  const handler = {} as typeof import("../../src/app/auth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/client/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/client">> = Specific
  const handler = {} as typeof import("../../src/app/client/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/coach/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/coach">> = Specific
  const handler = {} as typeof import("../../src/app/coach/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/onboarding/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/onboarding">> = Specific
  const handler = {} as typeof import("../../src/app/onboarding/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
